// Sunday scenarios restored through the same public Continue path used by players.
const known = ['ohayo', 'yoroshiku', 'sumimasen', 'matte', 'akete', 'ugoite', 'irete', 'tabetai'];
const seed = (place, flags = {}, extra = {}) => ({ day: 4, place, known, yen: 4000, ...extra,
  flags: { dorm_room_known: true, met_emi: true, d4_started: true, d3_time_seen: true, ...flags } });
const use = target => ({ type: 'use', target });
export default [
  { id: 'd4-fan-lever', description: 'Mechanical fan repair, then repeat without another payment.', seed: seed('gym'),
    choices: ['Free the fan’s starter lever.'], actions: [use('desk_fan'), use('desk_fan')],
    expect: { flags: { d4_fan_done: true, ticket_T0006: 'done' }, yen: 5000, period: 'morning' } },
  { id: 'd4-fan-magic', description: 'Known command starts the fan and receives one payment.', seed: seed('gym'),
    choices: ['Say 動いて (ugoite, move) to the fan.'], actions: [use('desk_fan')],
    expect: { flags: { d4_fan_done: true, d4_fan_magic: true }, yen: 5000 } },
  { id: 'd4-fan-defer', description: 'Leaving the stalled fan keeps its ticket open.', seed: seed('gym'),
    choices: ['Leave the fan for later.'], actions: [use('desk_fan')], expect: { flags: { d4_fan_done: false }, yen: 4000 } },
  { id: 'd4-display', description: 'Display cap reseated and verified by Rei, paid only once.', seed: seed('sports', {}, { period: 'afternoon' }),
    choices: ['Reseat the button cap.'], actions: [use('court_display'), use('court_display')],
    expect: { flags: { d4_display_done: true, d4_rei_intro: true }, yen: 5500, period: 'afternoon' } },
  { id: 'd4-display-defer', description: 'Loose display can wait while the courts stay open.', seed: seed('sports', {}, { period: 'afternoon' }),
    choices: ['Leave the display for later.'], actions: [use('court_display')], expect: { flags: { d4_display_done: false }, yen: 4000 } },
  { id: 'd4-tennis-aoi', description: 'Optional lesson and Aoi rally followed by a drink.',
    seed: seed('sports', { club_tennis: true }, { period: 'evening', node: 'd4_tennis_offer' }),
    choices: ['Ask which word means “together”.', 'Practise with Aoi.', 'Stay for a drink.'], actions: [],
    expect: { flags: { d4_played_aoi: true, d4_tennis_done: true, d3_aoi_intro: true, d4_rei_intro: true }, known: ['isshoni'], yen: 4000 } },
  { id: 'd4-tennis-rei', description: 'Skip the lesson and watch Rei demonstrate, then leave.',
    seed: seed('sports', { club_tennis: true }, { period: 'evening', node: 'd4_tennis_offer' }),
    choices: ['Take a racket.', 'Ask Rei to demonstrate a serve.', 'Head out.'], actions: [],
    expect: { flags: { d4_watched_rei: true, d4_tennis_done: true }, yen: 4000 } },
  { id: 'd4-tennis-return', description: 'Decline play, return to Aoi, then play without restarting introductions.',
    seed: seed('sports', { club_tennis: true }, { period: 'evening', node: 'd4_tennis_offer' }),
    choices: ['Come back to tennis later.', 'Take a racket.', 'Practise with Aoi.', 'Head out.'], actions: [use('aoi')],
    expect: { flags: { d4_played_aoi: true, d4_tennis_done: true }, yen: 4000 } },
  { id: 'd4-no-work-sleep', description: 'No tickets or clubs required to rest and sleep.', seed: seed('dorms'),
    choices: ['Rest until evening.', 'Sleep.'], actions: [use('computer'), use('bed')],
    expect: { flags: { d4_complete: true, d4_fan_done: false, d4_display_done: false }, ended: true, yen: 4000 } },
  { id: 'd4-booking-deferred', description: 'Saturday reset progress prints on Sunday and pays only once.',
    seed: seed('gym', { ticket_T0004: 'progress', d3_booking_restarted: true }),
    choices: ['Press Print for today’s bookings.'], actions: [use('gym_printer'), use('booking_terminal')],
    expect: { flags: { ticket_T0004: 'done', d3_booking_done: true }, known: ['dashite'], yen: 5500 } },
  { id: 'd4-booking-reload', description: 'Continue with a printed sheet before learning the printer word.',
    seed: seed('gym', { ticket_T0004: 'progress', d3_booking_restarted: true }, { node: 'd3_print' }),
    resumeAt: 'd3_dashite_word', resumeYenDelta: 1500, choices: [], actions: [],
    expect: { flags: { ticket_T0004: 'done', d3_booking_done: true }, known: ['dashite'], yen: 5500 } },
  { id: 'd4-monitor-deferred', description: 'Saturday monitor still repairable Sunday morning, never repaid.',
    seed: seed('gate', { ticket_T0003: 'progress', d3_monitor_seen: true }),
    choices: ['Seat the loose connector.'], actions: [use('guard_monitor'), use('guard_monitor')],
    expect: { flags: { ticket_T0003: 'done', d3_monitor_done: true }, yen: 5000 } },
  { id: 'd4-signoff-deferred', description: 'Saturday sign-off carried to the stationary Sunday carriage.',
    seed: seed('train', { d2_ticket_done: true, ticket_T0002: 'progress' }),
    choices: ['Run the final check.'], actions: [use('door_test'), use('door_test')],
    expect: { flags: { ticket_T0002: 'done', d3_station_done: true }, yen: 9000 } },
  { id: 'd4-tennis-reload', description: 'Continue after the rally retains the court staging and single completion.',
    seed: seed('sports', { club_tennis: true, d3_aoi_intro: true, d4_rei_intro: true }, { period: 'evening', node: 'd4_aoi_rally' }),
    resumeAt: 'd4_tennis_finish', choices: ['Stay for a drink.'], actions: [],
    expect: { flags: { d4_tennis_done: true, d4_played_aoi: true }, yen: 4000 } },
  { id: 'd4-nonmember', description: 'A nonmember can speak to Aoi without being enrolled or forced into play.',
    seed: seed('sports', {}, { period: 'evening' }), choices: [], actions: [use('aoi')],
    expect: { flags: { d4_tennis_done: false, club_tennis: false, d3_aoi_intro: true }, yen: 4000 } },
  { id: 'd4-pool-closed', description: 'Closed pool notice outside the pavilion, return to sports lane.',
    seed: seed('pool'), choices: [], actions: [use('pool_notice'), { ...use('changing_room'), settleAt: 'sports' }],
    expect: { flags: { d3_swim_done: false }, yen: 4000 } },
];
