// Every route uses real Monday hooks and the public Continue path.
const known = ['ohayo', 'yoroshiku', 'matte', 'dashite'];
const seed = (place, flags = {}, extra = {}) => ({ day: 5, place, known, yen: 4000, ...extra,
  flags: { dorm_room_known: true, d5_started: true, d3_time_seen: true, ...flags } });
const use = target => ({ type: 'use', target });
export default [
  { id: 'd5-label', description: 'Reception checks the full label and pays only once.', seed: seed('forecourt'),
    choices: ['Use the wider label format.'], actions: [use('kuro'), use('kuro')],
    expect: { flags: { d5_label_done: true, ticket_T0007: 'done' }, yen: 5500, period: 'morning' } },
  { id: 'd5-label-reload', description: 'Continue preserves the printed label before one confirmation payment.',
    seed: seed('forecourt', {}, { node: 'd5_label' }), resumeAt: 'd5_label_fix', resumeYenDelta: 1500,
    choices: ['Use the wider label format.'], actions: [use('kuro')],
    expect: { flags: { d5_label_done: true, ticket_T0007: 'done' }, yen: 5500, period: 'morning' } },
  { id: 'd5-label-defer', description: 'Leaving labels keeps the job open.', seed: seed('forecourt'),
    choices: ['Leave the labels for later.'], actions: [use('kuro')], expect: { flags: { d5_label_done: false }, yen: 4000 } },
  { id: 'd5-label-offhours', description: 'Reception cannot confirm a label at lunch.', seed: seed('forecourt', {}, { period: 'lunch' }),
    actions: [use('kuro')], expect: { flags: { d5_label_done: false }, yen: 4000 } },
  { id: 'd5-selector-key', description: 'Kenji verifies one row after the book is moved; one payment.', seed: seed('karaoke_booth', {}, { period: 'lunch' }),
    choices: ['Hold the stop key and lift the book.'], actions: [use('song_terminal'), use('song_terminal')],
    expect: { flags: { d5_selector_done: true, ticket_T0008: 'done' }, yen: 6000, period: 'lunch' } },
  { id: 'd5-selector-reload', description: 'Continue retains the moved book and stopped row before payment.',
    seed: seed('karaoke_booth', {}, { period: 'lunch', node: 'd5_selector' }), resumeAt: 'd5_selector_clear', resumeYenDelta: 2000,
    choices: ['Hold the stop key and lift the book.'], actions: [use('song_terminal')],
    expect: { flags: { d5_selector_done: true, ticket_T0008: 'done' }, yen: 6000, period: 'lunch' } },
  { id: 'd5-selector-offhours', description: 'The booth cannot confirm the selector after lunch.',
    seed: seed('karaoke_booth', {}, { period: 'evening' }), actions: [use('song_terminal')],
    expect: { flags: { d5_selector_done: false }, yen: 4000 } },
  { id: 'd5-selector-magic', description: 'The lunch command does not reveal the evening demonstration.', seed: seed('karaoke_booth', {}, { period: 'lunch' }),
    choices: ['Try 待って (matte, wait), then lift the book.'], actions: [use('song_terminal')],
    expect: { flags: { d5_selector_magic: true, d5_selector_done: true, d5_team_witnessed: false }, yen: 6000 } },
  { id: 'd5-defer', description: 'Ordinary drinks never count as witnessed magic.', seed: seed('office', {}, { period: 'evening' }),
    choices: ['Let’s just have ordinary drinks tonight.'], actions: [use('vending')],
    expect: { flags: { d5_team_witnessed: false, d5_reveal_done: false, d5_delivery_seen: false }, yen: 4000, period: 'evening' } },
  { id: 'd5-seen-resume', description: 'A saved delivered can resumes reactions without another first session.', seed: seed('office', { d5_delivery_seen: true }, { period: 'evening' }),
    choices: ['Finish with that first drink.'], actions: [use('vending')],
    expect: { flags: { d5_team_witnessed: true, d5_reveal_done: true }, yen: 4000, period: 'evening' } },
  { id: 'd5-witnessed-replay', description: 'A witnessed replay can end with ordinary drinks.', seed: seed('office', { d5_delivery_seen: true, d5_team_witnessed: true }, { period: 'evening' }),
    choices: ['Have an ordinary drink.'], actions: [use('vending')],
    expect: { flags: { d5_reveal_done: true }, yen: 4000, period: 'evening' } },
  { id: 'd5-guided-reload', description: 'Actual first delivery survives reload into its reactions.',
    seed: seed('office', {}, { period: 'evening', node: 'd5_drinks' }), delivery: 'first', resumeAt: 'd5_first_reactions',
    choices: ['Yes, if they want to.', 'Finish with that first drink.'], actions: [],
    expect: { flags: { d5_delivery_seen: true, d5_team_witnessed: true, d5_reveal_done: true }, yen: 4000, period: 'evening' } },
  { id: 'd5-guided-open-reload', description: 'Reload before delivery restarts guided play without witnessing unseen magic.',
    seed: seed('office', {}, { period: 'evening', node: 'd5_drinks' }), delivery: 'first', resumeInDelivery: true,
    choices: ['Yes, if they want to.', 'Finish with that first drink.'], actions: [],
    expect: { flags: { d5_delivery_seen: true, d5_team_witnessed: true, d5_reveal_done: true }, yen: 4000, period: 'evening' } },
  { id: 'd5-guided-cancel', description: 'Leaving before delivery preserves unseen and unrevealed state.',
    seed: seed('office', {}, { period: 'evening', node: 'd5_drinks' }), delivery: 'cancel',
    choices: ['Yes, if they want to.'], actions: [],
    expect: { flags: { d5_delivery_seen: false, d5_team_witnessed: false, d5_reveal_done: false }, yen: 4000, period: 'evening' } },
  { id: 'd5-rounds-empty', description: 'Optional rounds can exit without awarding anything.',
    seed: seed('office', { d5_delivery_seen: true, d5_team_witnessed: true }, { period: 'evening', node: 'd5_drinks' }), delivery: 'empty',
    choices: ['Try a few deliveries.'], actions: [],
    expect: { flags: { d5_last_recipient: '', d5_reveal_done: true }, yen: 4000, period: 'evening' } },
  ...['kenji', 'mori', 'mio'].map(recipient => ({ id: 'd5-rounds-' + recipient,
    description: 'Actual optional delivery returns the last recipient without world rewards.',
    seed: seed('office', { d5_delivery_seen: true, d5_team_witnessed: true, ticket_T0007: 'done' },
      { period: 'evening', node: 'd5_drinks', bonds: { kenji: 2, mori: 1 }, inv: [] }), delivery: recipient,
    choices: ['Try a few deliveries.'], actions: [],
    expect: { flags: { d5_last_recipient: recipient, d5_reveal_done: true, ticket_T0007: 'done' },
      yen: 4000, period: 'evening', bonds: { kenji: 2, mori: 1 }, inv: [] } })),
  { id: 'd5-missing-word', description: 'Ordinary print teaches dashite before a first guided delivery.',
    seed: seed('office', {}, { period: 'evening', node: 'd5_drinks', known: ['ohayo', 'yoroshiku', 'matte'] }), delivery: 'first',
    choices: ['Yes, if they want to.', 'Finish with that first drink.'], actions: [],
    expect: { flags: { d5_delivery_seen: true, d5_team_witnessed: true, d5_reveal_done: true },
      known: ['dashite'], yen: 4000, period: 'evening', nodes: ['d5_printer_lesson', 'd5_first_reactions'] } },
  { id: 'd5-known-lunch-magic', description: 'Known colleagues react to an observed lunch command only after the first delivery.',
    seed: seed('office', { met_kenji: true, met_mori: true, d5_selector_magic: true },
      { period: 'evening', node: 'd5_drinks', met: ['kenji', 'mori'] }), delivery: 'first',
    choices: ['Yes, if they want to.', 'Finish with that first drink.'], actions: [],
    expect: { flags: { d5_team_witnessed: true, d5_reveal_done: true }, yen: 4000, period: 'evening' } },
  { id: 'd5-no-work-sleep', description: 'No work, clubs or reveal required for Monday Sleep.', seed: seed('dorms'),
    choices: ['Rest until evening.', 'Sleep.'], actions: [use('computer'), use('bed')],
    expect: { flags: { d5_complete: true, d5_reveal_done: false, d5_label_done: false, d5_selector_done: false }, ended: true, yen: 4000 } },
];
