// Every route uses real Monday hooks and the public Continue path.
const known = ['ohayo', 'yoroshiku', 'matte', 'dashite'];
const seed = (place, flags = {}, extra = {}) => ({ day: 5, place, known, yen: 4000, ...extra,
  flags: { dorm_room_known: true, d5_started: true, d3_time_seen: true, ...flags } });
const use = target => ({ type: 'use', target });
export default [
  { id: 'd5-label', description: 'Reception checks the full label and pays only once.', seed: seed('forecourt'),
    choices: ['Use the wider label format.'], actions: [use('label_printer'), use('label_printer')],
    expect: { flags: { d5_label_done: true, ticket_T0007: 'done' }, yen: 5500, period: 'morning' } },
  { id: 'd5-label-defer', description: 'Leaving labels keeps the job open.', seed: seed('forecourt'),
    choices: ['Leave the labels for later.'], actions: [use('label_printer')], expect: { flags: { d5_label_done: false }, yen: 4000 } },
  { id: 'd5-label-offhours', description: 'Reception cannot confirm a label at lunch.', seed: seed('forecourt', {}, { period: 'lunch' }),
    actions: [use('label_printer')], expect: { flags: { d5_label_done: false }, yen: 4000 } },
  { id: 'd5-selector-key', description: 'Kenji verifies one row after the book is moved; one payment.', seed: seed('karaoke_booth', {}, { period: 'lunch' }),
    choices: ['Hold the stop key and lift the book.'], actions: [use('song_terminal'), use('song_terminal')],
    expect: { flags: { d5_selector_done: true, ticket_T0008: 'done' }, yen: 6000, period: 'lunch' } },
  { id: 'd5-selector-magic', description: 'The lunch command does not reveal the evening demonstration.', seed: seed('karaoke_booth', {}, { period: 'lunch' }),
    choices: ['Try 待って (matte, wait), then lift the book.'], actions: [use('song_terminal')],
    expect: { flags: { d5_selector_magic: true, d5_selector_done: true, d5_team_witnessed: false }, yen: 6000 } },
  { id: 'd5-defer', description: 'Ordinary drinks never count as witnessed magic.', seed: seed('office', {}, { period: 'evening' }),
    choices: ['Let’s just have ordinary drinks tonight.'], actions: [use('vending')],
    expect: { flags: { d5_team_witnessed: false, d5_reveal_done: false, d5_delivery_seen: false }, yen: 4000, period: 'evening' } },
  { id: 'd5-seen-resume', description: 'A saved delivered can resumes reactions without another first session.', seed: seed('office', { d5_delivery_seen: true }, { period: 'evening' }),
    choices: ['Finish with that first drink.'], actions: [use('vending')],
    expect: { flags: { d5_team_witnessed: true, d5_reveal_done: true }, yen: 4000, period: 'evening' } },
  { id: 'd5-witnessed-replay', description: 'A witnessed replay can end with ordinary drinks.', seed: seed('office', { d5_delivery_seen: true, d5_team_witnessed: true }, { period: 'evening' }),
    choices: ['Have an ordinary drink.'], actions: [use('vending')],
    expect: { flags: { d5_reveal_done: true }, yen: 4000, period: 'evening' } },
  { id: 'd5-guided-reload', description: 'Actual first delivery survives reload into its reactions.',
    seed: seed('office', {}, { period: 'evening', node: 'd5_drinks' }), delivery: 'first', resumeAt: 'd5_first_reactions',
    choices: ['Yes, if they want to.', 'Finish with that first drink.'], actions: [],
    expect: { flags: { d5_delivery_seen: true, d5_team_witnessed: true, d5_reveal_done: true }, yen: 4000, period: 'evening' } },
  { id: 'd5-guided-cancel', description: 'Leaving before delivery preserves unseen and unrevealed state.',
    seed: seed('office', {}, { period: 'evening', node: 'd5_drinks' }), delivery: 'cancel',
    choices: ['Yes, if they want to.'], actions: [],
    expect: { flags: { d5_delivery_seen: false, d5_team_witnessed: false, d5_reveal_done: false }, yen: 4000, period: 'evening' } },
  { id: 'd5-rounds-empty', description: 'Optional rounds can exit without awarding anything.',
    seed: seed('office', { d5_delivery_seen: true, d5_team_witnessed: true }, { period: 'evening', node: 'd5_drinks' }), delivery: 'empty',
    choices: ['Try a few deliveries.'], actions: [],
    expect: { flags: { d5_last_recipient: '', d5_reveal_done: true }, yen: 4000, period: 'evening' } },
  { id: 'd5-no-work-sleep', description: 'No work, clubs or reveal required for Monday Sleep.', seed: seed('dorms'),
    choices: ['Rest until evening.', 'Sleep.'], actions: [use('computer'), use('bed')],
    expect: { flags: { d5_complete: true, d5_reveal_done: false, d5_label_done: false, d5_selector_done: false }, ended: true, yen: 4000 } },
];
