import { newFrame, readCheckpoint } from './narrative/checkpoint.js';
import { flagKeys, KNOW_PREFIX } from './narrative/engine-flags.js';
const ENGINE_KEYS = flagKeys('game3d/js/runner.js');
import { DEFAULT_SPEAKERS } from './narrative/speakers.js';
// Runs the story files (game3d/story/*.js, format in game3d/story/FORMAT.md) against a place.
import { voiceThenBeat } from './ui.js';
import { ui, voice, sfx, setFace, PORTRAITS } from './ui.js';
import { WORDS, learn, known, cmdHTML, SAYABLE } from './lang.js';

export const flags = {};
// voice clips for overheard lines are generated by tools/voices.py as oh-<hash of the text>
export function lineKey(who, text = '') { return 'ln-' + heardKey(who + '|' + text).slice(3); }
export function heardKey(text = '') { let h = 5381; for (let i = 0; i < text.length; i++) h = ((h * 33) ^ text.charCodeAt(i)) >>> 0; return 'oh-' + h.toString(36); }
export const audioKeys = new Set();
fetch(new URL('../audio/index.json?v=' + (window.BUILD || ''), import.meta.url)).then((r) => (r.ok ? r.json() : [])).then((l) => l.forEach((k) => audioKeys.add(k))).catch(() => {});


// ---------- conditions ----------
const cache = new Map();
export function cond(expr) {
  if (expr === undefined || expr === null || expr === true) return true;
  if (expr === false) return false;
  let f = cache.get(expr);
  if (!f) {
    // identifiers become flag lookups; only these characters are allowed
    if (!/^[\w\s!&|()<>=.'"+-]*$/.test(expr)) { console.warn('bad condition', expr); return false; }
    const js = expr.replace(/'[^']*'|"[^"]*"|\b[A-Za-z_]\w*\b/g, (m) => (/^['"]/.test(m) || m === 'true' || m === 'false' ? m : `F(${JSON.stringify(m)})`));
    try { f = new Function('F', `return (${js});`); } catch (e) { console.warn('bad condition', expr, e); f = () => false; }
    cache.set(expr, f);
  }
  try { return !!f((k) => (k.startsWith(KNOW_PREFIX) ? known.has(k.slice(KNOW_PREFIX.length)) : (flags[k] ?? 0))); } catch { return false; }
}

// hooks that keep the current line on screen (they belong to it)
const KEEP_TALK = new Set(['type', 'expression', 'face', 'emote', 'voice', 'sound', 'hint', 'goal', 'learn', 'bond', 'meet', 'set', 'remember', 'fact', 'bondStep', 'relate']);
const DURABLE_HOOKS = new Set(['period', 'meet', 'buy', 'take', 'bond', 'bondStep', 'remember', 'fact', 'relate']);
const WORLD_HOOKS = new Set(['depart', 'bag', 'arrive', 'alight', 'cup', 'lunchSit', 'lunchOver', 'sitDown']);
export class Runner {
  constructor(game) { this.game = game; this.story = null; this.place = null; this.onceDone = new Set(); this.frames = []; this.queued = []; this.effectDepth = 0; }

  async load(name) {
    const tryImport = async (p) => { try { return (await import(p)).default; } catch (e) { if (!/Failed to fetch|Cannot find|404|error loading/i.test(String(e))) console.error(e); return null; } };
    const s = (await tryImport(`../story/${name}.js`)) || (await tryImport(`../story/placeholder/${name}.js`)) || { nodes: {}, on: {} };
    return s;
  }
  use(place, story) {
    this.place = place; this.story = story;
    flags[ENGINE_KEYS.place] = place.name;
    this.speakers = { ...DEFAULT_SPEAKERS, ...(story.speakers || {}) };
  }
  speaker(id) { return this.speakers[id] || { name: id }; }

  // find what should run for a trigger key; returns a node name or null
  // resolve(key, { peek: true }) only looks: has() must never use up a `once` trigger (it's asked every frame by the
  // Say chip, the markers and the zones; a peek used to spend them, so the real trigger found nothing)
  resolve(key, opts) { const t = this.entry(key, opts); return t ? t.node : null; }
  // the matching trigger entry itself, so a caller can read its options (a give: entry with keep: true is a refusal)
  entry(key, { peek = false } = {}) {
    const on = (this.story && this.story.on) || {};
    let v = on[key];
    if (v === undefined) return null;
    const list = Array.isArray(v) ? v : [v];
    for (const e of list) {
      const t = typeof e === 'string' ? { node: e } : e;
      if (t.once && this.onceDone.has(key + '>' + t.node)) continue;
      if (!cond(t.if)) continue;
      if (t.once && !peek) this.onceDone.add(key + '>' + t.node);
      return t;
    }
    return null;
  }
  has(key) { return !!this.resolve(key, { peek: true }); }
  // run a trigger inside a beat (locks walking); returns true if something ran
  trigger(key, { beat = true } = {}) {
    this.game.onTrigger?.(key);
    const node = this.resolve(key);
    if (!node) return false;
    // a new beat starts everyone on their neutral face: a face set on a line lasts for its scene only. It used to
    // last all day, so the listening portrait kept an old look (Jørgen: at the copier Eric looked surprised, still
    // from "Nineteen ninety-six?" in the ticket scene, and Mori flustered from the jam)
    const go = async () => { for (const who in PORTRAITS) setFace(who, undefined); await this.run(node, { trigger: key }); };
    // an event that fires while a scene is running waits for it to end
    if (beat && this.game.busy && /^(event|zone|near):/.test(key)) { this.enqueue(node, key); return true; }
    if (beat) this.game.beat(go); else go();
    return true;
  }

  enqueue(node, trigger = null, persist = true) {
    const queued = { node, trigger };
    this.queued.push(queued);
    this.game.queue.push(async () => {
      this.queued.splice(this.queued.indexOf(queued), 1);
      for (const who in PORTRAITS) setFace(who, undefined);
      await this.run(node, { trigger });
    });
    if (persist) this.persist();
  }

  get currentNode() { return this.frames.at(-1)?.node || ''; }
  snapshot() {
    return { onceDone: [...this.onceDone], execution: this.recoveryError ? structuredClone(this.pendingExecution) : this.frames.length
      ? structuredClone({ v: 3, place: this.place.name, frames: this.frames }) : this.pendingExecution || null,
      ...(this.queued.length ? { queued: structuredClone(this.queued) } : {}) };
  }
  restore(data) {
    this.recoveryError = null;
    this.onceDone = new Set(data?.onceDone || []);
    this.pendingExecution = data?.execution || null;
    this.pendingQueue = Array.isArray(data?.queued) ? data.queued : [];
  }
  async resume() {
    const frames = readCheckpoint(this.pendingExecution, this.place.name, this.story);
    if (this.pendingExecution && !frames) {
      this.failRecovery('This saved scene has changed and cannot be resumed.');
      return false;
    }
    this.pendingExecution = null;
    for (const queued of this.pendingQueue || []) {
      if (queued && Array.isArray(this.story.nodes[queued.node]) && (queued.trigger === null || typeof queued.trigger === 'string')) {
        this.enqueue(queued.node, queued.trigger, false);
      }
    }
    this.pendingQueue = [];
    if (!frames?.at(-1)?.staging) this.game.resumeWalks?.();
    if (frames) await this.run(frames[0].node, { restored: frames });
    else if (this.queued.length) await this.game.queue.shift()();
    else return false;
    return true;
  }
  persist() { this.onCheckpoint?.(); }
  failRecovery(message) {
    if (this.recoveryError) return;
    this.pendingExecution ||= this.snapshot().execution;
    this.recoveryError = message;
    this.game.onRecoveryError?.(message);
  }
  // Simulation operations may save internally. Their state and journal entry must be saved together.
  effect(context, key, fn) {
    const frame = context?.frame;
    if (!frame) return fn();
    if (frame.done.includes(key)) return;
    this.effectDepth++;
    let completed = false;
    try {
      const result = fn();
      if (result?.then) throw new Error('Checkpoint effect must be synchronous: ' + key);
      frame.done.push(key);
      completed = true;
      return result;
    } finally {
      this.effectDepth--;
      if (!this.effectDepth) { this.savePending = false; if (completed) this.persist(); }
    }
  }
  async run(node, { restored = null, trigger = null, replace = null } = {}) {
    const steps = this.story.nodes[node];
    if (!steps) { console.warn('missing node', node); return; }
    const frame = restored?.[0] || newFrame(node, steps, trigger || replace?.trigger);
    if (!restored) frame.staging = this.game.captureStaging?.() || null;
    const continuing = restored?.length > 1;
    const context = { frame, replaying: !!restored && !continuing && !!frame.staging,
      targets: continuing ? structuredClone(frame.cursors) : [], children: restored?.slice(1) || [] };
    frame.cursors = [];
    if (replace) this.frames.splice(this.frames.indexOf(replace), 1, frame);
    else this.frames.push(frame);
    try {
      if (context.replaying) this.game.restoreStaging(frame.staging);
      if (!continuing) {
        (this.trace = this.trace || []).push(node); if (this.trace.length > 20) this.trace.shift();
        this.effect(context, 'entry', () => this.onNodeStart?.(node));
        this.game.onNode?.(node, 'start');
      }
      await this.steps(steps, context);
      this.game.onNode?.(node, 'end');
      if (this.frames.includes(frame)) {
        const talk = /^talk:(.+)$/.exec(frame.trigger || '');
        if (talk) flags[ENGINE_KEYS.talked + talk[1]] = true;
      }
    } catch (error) {
      this.failRecovery('The scene could not finish.');
      throw error;
    } finally {
      const index = this.frames.indexOf(frame);
      if (index >= 0) this.frames.splice(index, 1);
    }
    if (!this.frames.length && !this.recoveryError) this.persist();
  }
  // returns 'go' when a jump happened, 'end' to stop
  async steps(list, context = null, path = []) {
    const target = context?.targets.find(c => JSON.stringify(c.path) === JSON.stringify(path));
    const cursor = { path, index: target?.index || 0, phase: target?.phase || 'step' };
    context?.frame.cursors.push(cursor);
    try {
      for (let index = cursor.index; index < list.length; index++) {
        cursor.index = index;
        cursor.phase = index === target?.index ? target.phase : 'step';
        const key = JSON.stringify([...path, index]);
        const result = await this.step(list[index], context, key, cursor);
        if (result === 'end' || result === 'go') return result;
      }
      return null;
    } catch (error) {
      // Capture suspended callers before unwinding removes their cursor paths.
      this.failRecovery('The scene could not finish.');
      throw error;
    } finally {
      if (context) context.frame.cursors.splice(context.frame.cursors.indexOf(cursor), 1);
    }
  }
  async call(node, context, key, cursor) {
    if (context?.frame.done.includes(key + ':call')) {
      if (context.replaying && context.frame.worldAfter[key + ':call']) this.game.restoreStaging(context.frame.worldAfter[key + ':call']);
      return;
    }
    const restored = context?.children.length ? context.children.splice(0) : null;
    await this.run(restored?.[0].node || node, { restored });
    if (context) {
      context.frame.worldAfter[key + ':call'] = this.game.captureStaging?.() || null;
      context.frame.done.push(key + ':call');
    }
    this.persist();
  }
  async jump(node, context) {
    await this.run(node, { replace: context?.frame || null });
    return 'go';
  }
  async step(s, context = null, key = '', cursor = { phase: 'step', path: [], index: 0 }) {
    this.lastStep = s;
    if (typeof s === 'string') return this.line(s);
    if (s.face && s.say) setFace(s.say, s.face);
    if (s.say) return this.sayLine(s.say, s.text, s.voice || (s.overheard ? heardKey(s.text) : undefined), s.name, s);
    if (s.choice) return this.choice(s, context, key, cursor);
    if (s.offer) return this.offer(s, context, key);
    if (s.learn) {
      this.effect(context, key + ':learn', () => {
        if (this.game.sim && !this.game.sim.taught[s.learn]) this.game.sim.taught[s.learn] = s.from || this.game.talkingTo;
        this.learnCmd(s.learn);
      });
      return null;
    }
    const continuing = cursor.phase;
    if (continuing === 'step') {
      if (s.set !== undefined) this.effect(context, key + ':set', () => { if (typeof s.set === 'string') flags[s.set] = true; else Object.assign(flags, s.set); });
      if (s.unset) this.effect(context, key + ':unset', () => { flags[s.unset] = false; });
      if (s.inc) this.effect(context, key + ':inc', () => { flags[s.inc] = (flags[s.inc] || 0) + 1; });
    }
    if (continuing !== 'call') {
      if (s.if !== undefined && (s.then || s.else)) {
        const branches = context?.frame.branches;
        const yes = branches && Object.hasOwn(branches, key) ? branches[key] : cond(s.if);
        if (branches) branches[key] = yes;
        cursor.phase = 'branch';
        const branch = yes ? 'then' : 'else';
        const result = await this.steps(s[branch] || [], context, [...cursor.path, cursor.index, branch]);
        if (result) return result;
      }
      if (s.go) return this.jump(s.go, context);
    }
    if (s.call) { cursor.phase = 'call'; await this.call(s.call, context, key, cursor); }
    if (s.wait) await this.game.wait(s.wait);
    if (s.do && !KEEP_TALK.has(s.do)) ui.closeTalk();
    if (s.do) await this.hook(s, context, key);
    if (s.end) return 'end';
    return null;
  }
  async line(str) {
    if (str.startsWith('>')) { await ui.say(null, str.replace(/^>\s*/, '')); return null; }
    const i = str.indexOf(': ');
    if (i > 0 && /^\w+$/.test(str.slice(0, i))) return this.sayLine(str.slice(0, i), str.slice(i + 2));
    await ui.say(null, str); return null;
  }
  async sayLine(who, text, voiceKey, name, s = {}) {
    const sp = name ? { ...this.speaker(who), name, role: '' } : this.speaker(who);
    this.game.talkingTo = who;
    if (!voiceKey && who !== 'eric' && !s.overheard) { const k = lineKey(who, text); if (audioKeys.has(k)) voiceKey = k; }
    if (!voiceKey && who === 'eric') { const k = lineKey(who, text); if (audioKeys.has(k)) voiceKey = k; }
    if (voiceKey && s.overheard && !audioKeys.has(voiceKey)) voiceKey = null;
    this.game.setHurry?.(false);
    const shown = ui.say(sp, text, { voiceKey, overheard: !!s.overheard, clear: s.clear, whoId: who, face: s.face });
    // test mode: record what an overheard line rendered, so the fast test fails on a known word shown garbled
    if (s.overheard && window.__test) {
      const line = document.querySelector('#talk .line');
      const garbled = [...line.querySelectorAll('.gx')].map((e) => e.dataset.c).join('');
      const bad = [...known].filter((id) => { const w = WORDS[id]; return w && [w.ja, ...(w.alias || [])].some((ja) => garbled.includes(ja)); });
      (window.__test.heard ||= []).push({ key: voiceKey, text, known: [...known], tokens: [...line.children].map((e) => `${e.className}:${e.textContent}`), garbledKnown: bad });
      if (bad.length) window.__test.errors.push(`known word shown garbled in "${text}": ${bad.join(', ')}`);
    }
    await shown;
    return null;
  }
  async choice(s, context, key, cursor) {
    const choices = context?.frame.choices;
    let selected = choices && Object.hasOwn(choices, key) ? choices[key] : null;
    if (selected === null) {
      const opts = s.choice.filter((o) => cond(o.if));
      let who = null, text = '', whoId = null;
      if (s.prompt) { const i = s.prompt.indexOf(': '); if (i > 0 && /^\w+$/.test(s.prompt.slice(0, i))) { whoId = s.prompt.slice(0, i); who = this.speaker(whoId); text = s.prompt.slice(i + 2); } else text = s.prompt.replace(/^>\s*/, ''); }
      this.game.setHurry?.(false);
      const pick = await ui.choose(who, text, opts.map((o) => ({ html: o.text.replace(/</g, '&lt;') })), { keepLine: !s.prompt, whoId });
      selected = s.choice.indexOf(opts[pick]);
      if (choices) choices[key] = selected;
    }
    const o = s.choice[selected];
    if (!o) throw new Error('Saved choice no longer exists');
    if (o.set) this.effect(context, key + ':choice-set', () => { if (typeof o.set === 'string') flags[o.set] = true; else Object.assign(flags, o.set); });
    if (o.call) { cursor.phase = 'choice-call'; await this.call(o.call, context, key, cursor); }
    if (o.go) return this.jump(o.go, context);
    return null;
  }
  async offer(s, context, key) {
    if (context?.frame.done.includes(key + ":offer")) return null;
    let who = null, text = '', whoId = null;
    if (s.line) { const i = s.line.indexOf(': '); if (i > 0 && /^\w+$/.test(s.line.slice(0, i))) { whoId = s.line.slice(0, i); who = this.speaker(whoId); text = s.line.slice(i + 2); } else text = s.line.replace(/^>\s*/, ''); }
    await ui.choose(who, text, [{ html: cmdHTML(s.offer), cls: 'cmdchip' }], { voiceKey: s.voice, whoId });
    const spoken = voice(WORDS[s.offer].voice);
    this.game.mioSays?.(s.offer);
    this.effect(context, key + ':offer', () => {
      this.game.sim?.taught && !this.game.sim.taught[s.offer] && who && (this.game.sim.taught[s.offer] = s.from || s.line.slice(0, s.line.indexOf(': ')));
      this.learnCmd(s.offer);
    });
    await voiceThenBeat(spoken, 350);
    return null;
  }
  learnCmd(id) {
    // the Say tip comes with the first word he can say (外人 gaijin is only understood, never said to anyone)
    const sayable = SAYABLE.includes(id), first = sayable && !SAYABLE.some((w) => known.has(w));
    if (learn(id)) {
      if (first) setTimeout(() => ui.introSay(), 600);
      if (this.game.learned) this.game.learned(WORDS[id].cmd ? 'command' : 'word'); else sfx('word');
      ui.refreshWords();
      ui.toast(`${sayable ? 'New command' : 'New word'}: <span class="jp">${WORDS[id].ja}</span> <span class="gl">${WORDS[id].ro}, ${WORDS[id].en}</span>`, 3400);
    }
  }
  async hook(s, context, key) {
    const h = this.game.hooks[s.do] || (this.place.hooks && this.place.hooks[s.do]);
    if (!h) { console.warn('unknown hook', s.do); return; }
    if (DURABLE_HOOKS.has(s.do)) {
      if (s.do === 'period' && context?.replaying && context.frame.done.includes(key + ':hook')) {
        const world = context.frame.worldAfter[key + ':hook'];
        if (world) this.game.restoreStaging(world);
      } else this.effect(context, key + ':hook', () => {
        const result = h(s);
        if (s.do === 'period' && context) context.frame.worldAfter[key + ':hook'] = this.game.captureStaging?.() || null;
        return result;
      });
    }
    else if (WORLD_HOOKS.has(s.do) && context) {
      if (context.frame.done.includes(key + ':hook') && !context.replaying) return;
      await h(s);
      if (!context.frame.done.includes(key + ':hook')) context.frame.done.push(key + ':hook');
      this.persist();
    }
    else if (s.do === 'type') {
      if (context?.frame.done.includes(key + ':hook')) return;
      await h(s, apply => this.effect(context, key + ':hook', apply));
    } else await h(s);
  }
  // non-blocking lines shown while something else happens (transition walks)
  async ambient(lines, gap = 2800) {
    for (const l of lines || []) {
      if (typeof l !== 'string') { await this.step(l); continue; }
      const i = l.indexOf(': ');
      const sp = i > 0 && /^\w+$/.test(l.slice(0, i)) ? this.speaker(l.slice(0, i)) : null;
      ui.caption(sp, sp ? l.slice(i + 2) : l.replace(/^>\s*/, ''));
      await this.game.wait(gap + Math.min(2500, l.length * 25));
    }
    ui.caption(null, '');
  }
}
