// Runs the story files (game3d/story/*.js, format in game3d/story/FORMAT.md) against a place.
import { ui, voice, sfx } from './ui.js';
import { WORDS, learn, known, cmdHTML } from './lang.js';

export const flags = {};
// voice clips for overheard lines are generated by tools/voices.py as oh-<hash of the text>
export function lineKey(who, text = '') { return 'ln-' + heardKey(who + '|' + text).slice(3); }
export function heardKey(text = '') { let h = 5381; for (let i = 0; i < text.length; i++) h = ((h * 33) ^ text.charCodeAt(i)) >>> 0; return 'oh-' + h.toString(36); }
export const audioKeys = new Set();
fetch(new URL('../audio/index.json', import.meta.url)).then((r) => (r.ok ? r.json() : [])).then((l) => l.forEach((k) => audioKeys.add(k))).catch(() => {});
const DEFAULT_SPEAKERS = {
  eric: { name: 'Eric', role: 'you', color: '#8fb4d8' },
  mio: { name: 'Mio', role: 'programmer', color: '#5fc6bf' },
  aoi: { name: 'Aoi', color: '#e79fb0' },
  kuroda: { name: 'Mr. Hamada', role: 'Accounts', color: '#b3a58f' },
  guard: { name: 'Mr. Ishibashi', role: 'security', color: '#8ea2c8' },
  kuro: { name: 'Kuro', role: 'reception', color: '#c3a7d6' },
  emi: { name: 'Emi', color: '#e0906f' },
  mori: { name: 'Mr. Mori', role: 'section chief', color: '#b9a3d3' },
  kenji: { name: 'Kenji', color: '#9fb6d8' },
  yui: { name: 'Yui', color: '#d7b27e' },
  sota: { name: 'Sota', color: '#9cc39a' },
  nao: { name: 'Nao', color: '#a9c3c0' },
  hiro: { name: 'Hiro', color: '#c0b39f' },
  ann: { name: 'Announcement', color: '#9aa9bd' },
  reader: { name: 'Man with a book', color: '#a8b0bf' },
  music: { name: 'Girl with headphones', color: '#a8b0bf' },
  bun: { name: 'Woman with a bun', color: '#a8b0bf' },
  youth: { name: 'Young man', color: '#a8b0bf' },
  stander: { name: 'Man by the door', color: '#a8b0bf' },
  commuter: { name: 'Commuter', color: '#a8b0bf' },
  rei: { name: 'Rei', role: 'Sales', color: '#c9ced8' },
  kanae: { name: 'Kanae', color: '#f0a060' },
  sales1: { name: 'Man from Sales', color: '#a8b0bf' },
  sales2: { name: 'Woman from Sales', color: '#a8b0bf' },
  gatev: { name: 'Gate', role: 'recorded voice', color: '#7fd0c8' },
  reitext: { name: 'Rei', role: 'message', color: '#c9ced8', phone: true },
};

// ---------- conditions ----------
const cache = new Map();
export function cond(expr) {
  if (expr === undefined || expr === null || expr === true) return true;
  if (expr === false) return false;
  let f = cache.get(expr);
  if (!f) {
    // identifiers become flag lookups; only these characters are allowed
    if (!/^[\w\s!&|()<>=.'"+-]*$/.test(expr)) { console.warn('bad condition', expr); return false; }
    const js = expr.replace(/'[^']*'|"[^"]*"|\b[A-Za-z_]\w*\b/g, (m) => (/^['"]/.test(m) || m === 'true' || m === 'false' ? m : `F(${JSON.stringify(m)})`));
    try { f = new Function('F', `return (${js});`); } catch (e) { console.warn('bad condition', expr, e); f = () => false; }
    cache.set(expr, f);
  }
  try { return !!f((k) => (k.startsWith('know_') ? known.has(k.slice(5)) : (flags[k] ?? 0))); } catch { return false; }
}

export class Runner {
  constructor(game) { this.game = game; this.story = null; this.place = null; this.onceDone = new Set(); }

  async load(name) {
    const tryImport = async (p) => { try { return (await import(p)).default; } catch (e) { if (!/Failed to fetch|Cannot find|404|error loading/i.test(String(e))) console.error(e); return null; } };
    const s = (await tryImport(`../story/${name}.js`)) || (await tryImport(`../story/placeholder/${name}.js`)) || { nodes: {}, on: {} };
    return s;
  }
  use(place, story) {
    this.place = place; this.story = story;
    flags.place = place.name;
    this.speakers = { ...DEFAULT_SPEAKERS, ...(story.speakers || {}) };
  }
  speaker(id) { return this.speakers[id] || { name: id }; }

  // find what should run for a trigger key; returns a node name or null
  resolve(key) {
    const on = (this.story && this.story.on) || {};
    let v = on[key];
    if (v === undefined) return null;
    const list = Array.isArray(v) ? v : [v];
    for (const e of list) {
      const t = typeof e === 'string' ? { node: e } : e;
      if (t.once && this.onceDone.has(key + '>' + t.node)) continue;
      if (!cond(t.if)) continue;
      if (t.once) this.onceDone.add(key + '>' + t.node);
      return t.node;
    }
    return null;
  }
  has(key) { return !!this.resolve(key); }
  // run a trigger inside a beat (locks walking); returns true if something ran
  trigger(key, { beat = true } = {}) {
    const node = this.resolve(key);
    if (!node) return false;
    const m = /^talk:(.+)$/.exec(key);
    const go = async () => { await this.run(node); if (m) flags['talked_' + m[1]] = true; };
    // an event that fires while a scene is running waits for it to end
    if (beat && this.game.busy && /^(event|zone|near):/.test(key)) { this.game.queue.push(go); return true; }
    if (beat) this.game.beat(go); else go();
    return true;
  }

  async run(node) {
    (this.trace = this.trace || []).push(node); if (this.trace.length > 20) this.trace.shift();
    const steps = this.story.nodes[node];
    if (!steps) { console.warn('missing node', node); return; }
    await this.steps(steps);
  }
  // returns 'go' when a jump happened, 'end' to stop
  async steps(list) {
    for (const s of list) {
      const r = await this.step(s);
      if (r === 'end' || r === 'go') return r;
    }
    return null;
  }
  async step(s) {
    this.lastStep = s;
    if (typeof s === 'string') return this.line(s);
    if (s.say) return this.sayLine(s.say, s.text, s.voice || (s.overheard ? heardKey(s.text) : undefined), s.name, s);
    if (s.choice) return this.choice(s);
    if (s.offer) return this.offer(s);
    if (s.learn) { if (this.game.sim && !this.game.sim.taught[s.learn]) this.game.sim.taught[s.learn] = s.from || this.game.talkingTo; this.learnCmd(s.learn); return null; }
    if (s.set !== undefined) { if (typeof s.set === 'string') flags[s.set] = true; else Object.assign(flags, s.set); }
    if (s.unset) flags[s.unset] = false;
    if (s.inc) flags[s.inc] = (flags[s.inc] || 0) + 1;
    if (s.if !== undefined && (s.then || s.else)) { const r = await this.steps(cond(s.if) ? (s.then || []) : (s.else || [])); if (r) return r; }
    if (s.go) { await this.run(s.go); return 'go'; }
    if (s.call) await this.run(s.call);
    if (s.wait) await this.game.wait(s.wait);
    if (s.do) await this.hook(s);
    if (s.end) return 'end';
    return null;
  }
  async line(str) {
    if (str.startsWith('>')) { await ui.say(null, str.replace(/^>\s*/, '')); return null; }
    const i = str.indexOf(': ');
    if (i > 0 && /^\w+$/.test(str.slice(0, i))) return this.sayLine(str.slice(0, i), str.slice(i + 2));
    await ui.say(null, str); return null;
  }
  async sayLine(who, text, voiceKey, name, s = {}) {
    const sp = name ? { ...this.speaker(who), name, role: '' } : this.speaker(who);
    this.game.talkingTo = who;
    if (!voiceKey && who !== 'eric' && !s.overheard) { const k = lineKey(who, text); if (audioKeys.has(k)) voiceKey = k; }
    if (!voiceKey && who === 'eric') { const k = lineKey(who, text); if (audioKeys.has(k)) voiceKey = k; }
    if (voiceKey && s.overheard && !audioKeys.has(voiceKey)) voiceKey = null;
    await ui.say(sp, text, { voiceKey, overheard: !!s.overheard, clear: s.clear });
    return null;
  }
  async choice(s) {
    const opts = s.choice.filter((o) => cond(o.if));
    let who = null, text = '';
    if (s.prompt) { const i = s.prompt.indexOf(': '); if (i > 0 && /^\w+$/.test(s.prompt.slice(0, i))) { who = this.speaker(s.prompt.slice(0, i)); text = s.prompt.slice(i + 2); } else text = s.prompt.replace(/^>\s*/, ''); }
    const pick = await ui.choose(who, text, opts.map((o) => ({ html: o.text.replace(/</g, '&lt;') })), { keepLine: !s.prompt });
    const o = opts[pick];
    if (o.set) { if (typeof o.set === 'string') flags[o.set] = true; else Object.assign(flags, o.set); }
    if (o.call) await this.run(o.call);
    if (o.go) { await this.run(o.go); return 'go'; }
    return null;
  }
  async offer(s) {
    let who = null, text = '';
    if (s.line) { const i = s.line.indexOf(': '); if (i > 0 && /^\w+$/.test(s.line.slice(0, i))) { who = this.speaker(s.line.slice(0, i)); text = s.line.slice(i + 2); } else text = s.line.replace(/^>\s*/, ''); }
    await ui.choose(who, text, [{ html: cmdHTML(s.offer), cls: 'cmdchip' }], { voiceKey: s.voice });
    voice(WORDS[s.offer].voice);
    this.game.mioSays?.(s.offer);
    this.game.sim?.taught && !this.game.sim.taught[s.offer] && who && (this.game.sim.taught[s.offer] = s.from || s.line.slice(0, s.line.indexOf(': ')));
    this.learnCmd(s.offer);
    await this.game.wait(600);
    return null;
  }
  learnCmd(id) {
    const first = known.size === 0;
    if (learn(id)) {
      if (first) setTimeout(() => ui.introSay(), 600);
      sfx('word'); ui.refreshWords();
      ui.toast(`New command: <span class="jp">${WORDS[id].ja}</span> <span class="gl">${WORDS[id].ro}, ${WORDS[id].en}</span>`, 3400);
    }
  }
  async hook(s) {
    const h = this.game.hooks[s.do] || (this.place.hooks && this.place.hooks[s.do]);
    if (!h) { console.warn('unknown hook', s.do); return; }
    await h(s);
  }
  // non-blocking lines shown while something else happens (transition walks)
  async ambient(lines, gap = 2800) {
    for (const l of lines || []) {
      if (typeof l !== 'string') { await this.step(l); continue; }
      const i = l.indexOf(': ');
      const sp = i > 0 && /^\w+$/.test(l.slice(0, i)) ? this.speaker(l.slice(0, i)) : null;
      ui.caption(sp, sp ? l.slice(i + 2) : l.replace(/^>\s*/, ''));
      await this.game.wait(gap + Math.min(2500, l.length * 25));
    }
    ui.caption(null, '');
  }
}
