// Sunday smoke route: one repair, tennis, and the room's independent evening/Sleep path.
export const DAY4_ROUTE = [
  ['dorms', 'computer', ['Open repair requests']],
  ['dorms', 'door_out'],
  ['dorms', 'stairs_down'],
  ['dorm_court', 'street_gate'],
  ['east_lane', 'plaza_lane'],
  ['plaza', 'noticeboard'],
  ['plaza', 'dorm_lane'],
  ['east_lane', 'north_street'],
  ['sports', 'gym'],
  ['gym', 'desk_fan', ['Free the fan']],
  ['gym', 'gym_door'],
  ['sports', 'north_street'],
  ['east_lane', 'dorm_gate'],
  ['dorm_court', 'stairs'],
  ['dorms', 'computer', ['Rest until evening']],
  ['dorms', 'door_out'],
  ['dorms', 'stairs_down'],
  ['dorm_court', 'street_gate'],
  ['east_lane', 'north_street'],
  ['sports', 'court_display', ['Reseat the button']],
  ['sports', 'aoi', ['Ask which word', 'Practise with Aoi', 'Stay for a drink']],
  ['sports', 'north_street'],
  ['east_lane', 'dorm_gate'],
  ['dorm_court', 'stairs'],
  ['dorms', 'bed', ['Sleep.']],
];
