"""The opening's karaoke data: tools/opening/karaoke.json (per-syllable timings of the sung lines, placed by hand
from the vocal stem's spectrogram, pitch and onsets) plus the English lines, written as game3d/opening/lyrics.js.
Run: python3 tools/opening/lyrics_js.py"""
import json, os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
EN = {
    1: 'The morning monorail, the view outside the window',
    2: "A town I don't know yet is shining",
    3: 'An ID card in my pocket',
    4: 'From today, this is where I work',
    5: 'Nice to meet you, new town',
    6: 'Words become my magic',
    7: 'With one small “help me”',
    8: 'the world starts to move, just a little',
}
lines = json.load(open(os.path.join(ROOT, 'tools/opening/karaoke.json')))
out = []
for l in lines:
    segs = []
    for s in l['segs']:
        if s['text'] == ' ':
            segs.append({'text': ' '})
            continue
        seg = {'text': s['text'], 't0': s['t0'], 't1': s['t1']}
        if s.get('kana') and s['kana'] != s['text'].strip('「」'):
            seg['kana'] = s['kana']
        if s.get('moras'):
            seg['moras'] = s['moras']
        segs.append(seg)
    out.append({'line': l['line'], 'jp': l['jp'], 'en': EN[l['line']], 'segs': segs})
js = ('// The sung lines with per-syllable timings (tools/opening/karaoke.json) and their English.\n'
      '// Generated by tools/opening/lyrics_js.py; edit the JSON or the script, not this file.\n'
      'export const LYRICS = ' + json.dumps(out, ensure_ascii=False, separators=(',', ':')) + ';\n')
open(os.path.join(ROOT, 'game3d/opening/lyrics.js'), 'w').write(js)
print(len(out), 'lines')
