"""Revised shot list for the 89.6 s TV edit (game/audio/music/opening-tv.mp3), under the 2026-09-25 rules:
inside the train = side view only (sea and sky), progress toward the island only from outside, prompts describe only what
is visible, his images are references only. Each shot names its source: picked (already approved), cloud master (new,
Replicate), derived (made locally from an approved master), sprite (approved character art), drawn (made in code).
Only shot 2 is being produced now (the pilot)."""

# (n, time in the edit, lyric, source, what we see, staging note, visible-only prompt or build note)
SHOTS = [
    (1, '0.0–3.6', '', 'picked: sky-tall-12', 'Morning sky, tilt down to the sea horizon and the sun.',
     'Camera high over the bay facing the sunrise; nothing but sky, sun and sea.', 'Tilt on the tall plate, slow cloud parallax, flare as the sun enters.'),
    (2, '3.6–5.2', '', 'cloud master (PILOT)', 'The monorail on its curving beam over the bay, heading into the island city.',
     'Camera high above the bay, off to the side; beam on pillars curves from lower left to the city on the right horizon; four-car train on the beam, driver\'s cab at the right end (toward the city), flat back at the left; sun low left of the city.',
     'See the pilot section above.'),
    (3, '5.2–6.8', '', 'picked: oncoming2-216', 'Low angle, the train comes over us.',
     'Camera at a pillar foot looking back along the beam; the city is behind the camera.', 'Roll and push, speed lines. Needs the straight-line cloud repeat painted out (local).'),
    (4, '6.8–8.4', '', 'derived from shot 2', 'Outside, the carriage side sliding past, sun in its windows.',
     'Camera level with the beam, square-on to one carriage; the car fills the frame end to end.',
     'img2img from our approved exterior master: "showing a view looking directly at one carriage from the side, carriage covering the image end to end, window reflecting only sea and sky."'),
    (5, '8.4–11.6', '', 'picked: mc-window2-266', 'Him at the side window, sea far below.',
     'Side view only: sea and sky out of the window; no track visible.', 'Slow push, light sweep across his face.'),
    (6, '11.6–12.8', '', 'drawn', 'Small 天川 logo flash and the first staff credit.', 'Over a soft crop of shot 1.', 'No "opening theme" label.'),
    (7, '12.8–16.0', '朝のモノレール 窓の外', 'picked: mc-window2-266 (closer)', 'Closer on him; pillar shadows pass on the beat.',
     'Same camera, tighter crop; shadows move in the direction of travel.', 'Credit: story.'),
    (8, '16.0–18.8', '', 'derived from shot 2', 'The train on the beam, closer.', 'Crop of the master toward the train, repainted at 0.35–0.5.', 'Glints on the water on the beat.'),
    (9, '18.8–21.2', '知らない街が 光ってる', 'derived from shot 2', 'The city across the water, shining.', 'Crop of the master toward the city, repainted.', 'Glints on the glass on the beat. Credit: art.'),
    (10, '21.2–24.4', '', 'cloud master', 'The train entering the island between the first towers.',
     'Camera outside at the island edge, facing along the route inland; the train comes toward the camera onto the island, the sea behind it.',
     'A white four-car monorail train on a concrete beam between glass office towers, its driver\'s cab toward the camera. Behind it the beam runs back over the sea. Early morning, low sun.'),
    (11, '24.4–27.6', 'ポケットに IDカード', 'drawn', 'The ID card rises out of his pocket, rack focus, glint.', 'Drawn card over a blurred crop of shot 5.', 'His photo from the approved sprite.'),
    (12, '27.6–29.2', '', 'drawn', 'The phone\'s new-hire app: ようこそ, the island map, his dorm.', 'Phone looks like a phone; no odd shapes.', 'Redo the map without the circle.'),
    (13, '29.2–31.6', '', 'cloud master', 'Arrival: the station platform, the train stopped, doors open.',
     'Camera on the platform, square-on to the train; platform doors open; sky above the roof.',
     'A white monorail car stopped at an elevated station platform, glass platform doors and the car doors open, bright empty interior, tiled floor with a yellow tactile strip, a white steel canopy, blue morning sky.'),
    (14, '31.6–34.0', '今日からここで 働くよ', 'picked location: gate-lobby-2103', 'The security gate; the card taps, the light goes teal.', 'Approved gate plate; drawn card and glow.', 'Credit: song.'),
    (15, '34.0–35.6', '', 'cloud master', 'He looks up: a glass tower rising into the morning sky.',
     'Camera at street level looking straight up one tower; the top inside the frame with sky above.',
     'Looking straight up the side of one glass office tower to a clear morning sky, the top of the tower inside the frame, white clouds, low sun catching the glass.'),
    (16, '35.6–37.2', '', 'sprite (needs approval: eyes-open variant)', 'His face, eyes up; white flash on the chorus.', 'Approved design; eyes repainted open.', ''),
    (17, '37.2–40.4', 'はじめまして 新しい街', 'cloud master', 'The reveal: the whole island company city from the water.',
     'Camera low over the water facing the island; beam curves in from the left; sun low; no train.',
     'A man-made island city of glass office towers seen from low over a calm bay, an elevated concrete monorail beam on pillars curving in from the left foreground to the island, low morning sun, sunlight glitter on the sea.'),
    (18, '40.4–42.0', '', 'picked: oncoming2-216', 'The train overhead again, whip.', '', 'Speed lines, whip pan out.'),
    (19, '42.0–43.6', '', 'sprite', 'Pose reveal: the new hire.', 'Graphic card.', ''),
    (20, '43.6–47.6', '言葉が僕の 魔法になる', 'sprite + drawn', 'ことば and まほう draw themselves in light around him.', 'Graphic, dark teal.', ''),
    (21, '47.6–50.0', '', 'drawn', 'A stream of glowing kana wipes the frame.', '', ''),
    (22, '50.0–53.2', '小さな「手伝って」で', 'picked location: copyroom-copier-4203', 'The copy room: てつだって glows, the copier wakes, pages fly.', 'Approved copy room.', ''),
    (23, '53.2–56.8', '', 'sprite', 'Emi through flying paper.', 'Graphic card.', ''),
    (24, '56.8–59.6', '世界が少し 動き出す', 'derived from approved plates', 'Beat montage: gate, copier, train, glints: things start to move.', '', ''),
    (25, '59.6–62.8', '', 'shot 2', 'Wide again, pulling back.', '', ''),
    (26, '62.8–66.0', '', 'picked: mc-window2-266', 'Him at the window; light washes the frame.', '', ''),
    (27, '66.0–68.4', '地下の部屋に ゲームの音', 'location (the basement office is being redone)', 'The basement office.', 'Wait for the approved basement office.', ''),
    (28, '68.4–70.8', '', 'sprite', 'Mio with monitor light changing on the beat.', 'Graphic card with screen glow.', ''),
    (29, '70.8–72.8', 'リーダーは笑って「いいね」って', 'sprite', 'Emi laughs, いいね pops.', 'Graphic sunburst.', ''),
    (30, '72.8–78.8', '', 'sprite', 'Rei.', 'Graphic card.', ''),
    (31, '78.8–83.6', '世界が少し 動き出す', 'sprites', 'The cast in two rows against the sunrise, silhouettes filling with colour on the beat.', '', ''),
    (32, '83.6–86.8', '', 'picked: sky-tall-12', 'Tilt up into the sky.', '', ''),
    (33, '86.8–89.6', '', 'drawn', '天川 / AMAKAWA logo on the last downbeat, staff-style credits, hold, fade.', '', ''),
]
CLOUD_MASTERS = [2, 10, 13, 15, 17]
