// Optional B2 investigation. The queue and comparison, not vocabulary, authorize the intervention.
export default {
  on: { 'ask:mio-sender': 'sender_offer', 'talk:sender_console': 'sender_console', 'talk:sender_live': 'sender_live' },
  nodes: {
    sender_live: [{ do: 'sender', action: 'live' }, { go: 'sender_leave' }],
    sender_offer: [
      { do: 'sender', action: 'available' },
      { if: '!sender_available', then: [{ end: true }] },
      { if: 'sender_delivered', then: [{ go: 'sender_later' }] },
      { if: 'sender_offered', then: [{ go: 'sender_offer_choices' }] },
      { do: 'sender', action: 'desk' },
      { if: '!sender_action_ok', then: [{ end: true }] },
      { say: 'mio', emo: 'tired', text: "The timesheet sender. It comes back up before I can see what made it fall over." },
      { do: 'sender', action: 'offer' },
      { do: 'sender', action: 'screen' },
      { say: 'eric', emo: 'curious', text: 'Has any of that gone through?' },
      { say: 'mio', emo: 'casual', text: "Not yet. The green light only means it's back on." },
      { say: 'mio', emo: 'casual', text: 'Can you have a look at the other screen while I try it here?' },
      { go: 'sender_offer_choices' },
    ],
    sender_offer_choices: [
      { choice: [
        { text: 'Show me.', go: 'sender_accept', if: '!sender_remark_heard' },
        { text: 'Look at the console.', go: 'sender_leave', if: 'sender_remark_heard' },
        { text: 'How do you say “not yet”?', go: 'sender_word', if: '!know_mada' },
        { text: 'Give me a minute.', go: 'sender_leave' },
      ] },
    ],
    sender_word: [
      { say: 'mio', emo: 'slow', slow: true, text: '{mada}. Not yet.' },
      { choice: [
        { text: 'Try “mada”.', go: 'sender_practice' },
        { text: 'Leave it for now.', go: 'sender_word_return' },
      ] },
    ],
    sender_practice: [
      { do: 'type', word: 'mada', from: 'mio', prompt: 'Try “not yet”.' },
      { say: 'mio', emo: 'casual', text: 'Mm. Still waiting.' },
      { go: 'sender_word_return' },
    ],
    sender_word_return: [{ if: 'sender_delivered', then: [{ go: 'sender_later' }] }, { go: 'sender_offer_choices' }],
    sender_accept: [
      { do: 'sender', action: 'door' },
      { if: '!sender_action_ok', then: [{ go: 'sender_leave' }] },
      { say: 'mori', overheard: true, emo: 'polite', text: 'そちらには、{mada}残っていますよ。' },
      { do: 'sender', action: 'memory' },
      { do: 'save' },
      { go: 'sender_leave' },
    ],
    sender_leave: [{ do: 'sender', action: 'release' }, { do: 'save' }],
    sender_console: [
      { do: 'sender', action: 'wake' },
      { if: '!sender_action_ok', then: [{ end: true }] },
      { go: 'sender_inspect' },
    ],
    sender_inspect: [
      { do: 'sender', action: 'inspect' },
      { if: 'sender_wants_mori', then: [{ go: 'sender_interpret' }] },
      { if: 'sender_compared && !sender_comparison_shown', then: [{ go: 'sender_compare' }] },
      { if: 'sender_delivered && !sender_result_shown', then: [{ go: 'sender_delivered' }] },
      { if: 'sender_failed && !sender_failure_shown', then: [{ go: 'sender_failed_once' }] },
      { go: 'sender_leave' },
    ],
    sender_interpret: [
      { do: 'sender', action: 'mori' },
      { if: '!sender_action_ok', then: [{ go: 'sender_leave' }] },
      { say: 'eric', emo: 'curious', text: "{mada}... You mean it's still there?" },
      { do: 'sender', action: 'point' },
      { say: 'mori', overheard: true, emo: 'polite', text: 'はい。上に前の分が残っています。' },
      { if: 'sender_delivered', then: [{ say: 'eric', emo: 'curious', text: "That's why you sent me over there." }], else: [{ say: 'eric', emo: 'curious', text: "I'll look further back." }] },
      { set: 'sender_interpreted' },
      { do: 'sender', action: 'moriHome' },
      { go: 'sender_inspect' },
    ],
    sender_compare: [
      { do: 'sender', action: 'moriHome' },
      { do: 'sender', action: 'mio' },
      { if: '!sender_action_ok', then: [{ go: 'sender_leave' }] },
      { say: 'eric', emo: 'curious', text: 'Both runs stop at this one.' },
      { say: 'mio', emo: 'curious', text: 'Let me see.' },
      { do: 'sender', action: 'showComparison' },
      { say: 'mio', emo: 'casual', text: "We can hold that one here. It won't delete it." },
      { set: 'sender_comparison_shown' },
      { choice: [
        { text: 'Hold 25 and try the others.', go: 'sender_try_hold' },
        { text: 'Try again with everything.', go: 'sender_try_all' },
        { text: 'Leave it for now.', go: 'sender_mio_leave' },
      ] },
    ],
    sender_try_hold: [{ do: 'sender', action: 'hold25' }, { go: 'sender_try' }],
    sender_try_all: [{ do: 'sender', action: 'releaseHold' }, { go: 'sender_try' }],
    sender_try: [{ do: 'sender', action: 'retry' }, { go: 'sender_inspect' }],
    sender_failed_once: [
      { do: 'sender', action: 'mio' },
      { if: '!sender_action_ok', then: [{ go: 'sender_leave' }] },
      { say: 'mio', emo: 'tired', text: "Same place. I'll leave it stopped while you look." },
      { set: 'sender_failure_shown' },
      { go: 'sender_mio_leave' },
    ],
    sender_delivered: [
      { do: 'sender', action: 'payoff' },
      { if: '!sender_action_ok', then: [{ go: 'sender_leave' }] },
      { say: 'mio', emo: 'casual', text: 'Okay. Those have gone through.' },
      { say: 'eric', emo: 'curious', text: 'And this one stays here?' },
      { say: 'mio', emo: 'casual', text: 'Yes. I can look at it without holding everyone else up.' },
      { do: 'sender', action: 'note' },
      { if: '!sender_action_ok', then: [{ go: 'sender_leave' }] },
      { set: 'sender_note_kept' },
      { say: 'mio', emo: 'warm', text: 'Thanks. I was about to sit through that restart again.' },
      { set: 'sender_result_shown' },
      { go: 'sender_leave' },
    ],
    sender_mio_leave: [{ do: 'sender', action: 'mioHome' }, { go: 'sender_leave' }],
    sender_later: [
      { do: 'sender', action: 'available' },
      { if: '!sender_available || !sender_delivered', then: [{ end: true }] },
      { do: 'sender', action: 'desk' },
      { if: '!sender_action_ok', then: [{ end: true }] },
      { choice: [
        { text: 'Ask about the held item.', go: 'sender_later_reply', if: 'sender_partial' },
        { text: '{mada}?', go: 'sender_later_word', if: 'know_mada' },
        { text: 'How do you say “not yet”?', go: 'sender_word', if: '!know_mada' },
        { text: 'Leave it for now.', go: 'sender_leave' },
      ] },
    ],
    sender_later_word: [{ say: 'eric', emo: 'curious', text: '{mada}?' }, { go: 'sender_later_reply' }],
    sender_later_reply: [
      { say: 'mio', emo: 'casual', text: 'Still here, yes. The others went through.' },
      { say: 'mio', emo: 'curious', text: "I've kept the original. I want to know what it did before I change it." },
      { go: 'sender_leave' },
    ],
  },
};
