"""Builds data.js for the mechanics prototypes from data/lang (JMdict, KANJIDIC2, grammar list, profiles).
Run from the repo root or this folder: python3 proto2/mechanics/build_data.py"""
import json, re, pathlib
here = pathlib.Path(__file__).resolve().parent
lang = here.parent.parent / 'data' / 'lang'
kanji = json.load(open(lang / 'kanji.json'))['kanji']
words = json.load(open(lang / 'words.json'))['words']
grammar = json.load(open(lang / 'grammar.json'))
points = grammar['points'] if 'points' in grammar else [v for v in grammar.values() if isinstance(v, list)][0]
profiles = json.load(open(lang / 'profiles.json'))['profiles']

# Kanji tier from the JLPT level: N5 -> 1, N4 -> 2, N3 -> 3, N2 -> 4, N1 or none -> 5.
tier = {k: (6 - v['n']) if v.get('n') else 5 for k, v in kanji.items()}
# Keys used by the prototypes: JLPT level and the JMdict gloss for each.
lex_src = (here / 'lexicon.js').read_text()
keys = re.findall(r"'([^']+)': \{", lex_src)
by_form = {}
for wid, w in words.items():
    for f in (w.get('k') or []) + (w.get('r') or []):
        cur = by_form.get(f)
        if cur is None or (w.get('f') or 1e9) < (cur.get('f') or 1e9): by_form[f] = w
info = {}
for k in keys:
    w = by_form.get(k)
    if w: info[k] = {'n': w.get('n'), 'g': w.get('g')}
gram = {p['id']: p['name'] for p in points}
presets = []
for pid, lv, reading in (('beginner', 0, 'romaji'), ('jorgen', 1, 'kana'), ('n3', 4, 'kana')):
    p = profiles[pid]
    presets.append({'id': pid, 'label': p['name'].split(':')[0].split(' (')[0], 'full': p['name'], 'level': lv, 'reading': reading,
                    'readable': p['kanji'].get('readable', ''), 'learning': p['kanji'].get('learning', '')})
out = ['// Generated by build_data.py from data/lang. Do not edit by hand.',
       '// JMdict and KANJIDIC2 data: property of the Electronic Dictionary Research and Development Group, CC BY-SA 4.0.',
       'export const KANJI_TIER = ' + json.dumps(tier, ensure_ascii=False, separators=(',', ':')) + ';',
       'export const WORD_INFO = ' + json.dumps(info, ensure_ascii=False, separators=(',', ':')) + ';',
       'export const GRAMMAR = ' + json.dumps(gram, ensure_ascii=False, separators=(',', ':')) + ';',
       'export const PRESETS = ' + json.dumps(presets, ensure_ascii=False, separators=(',', ':')) + ';', '']
(here / 'data.js').write_text('\n'.join(out))
print(len(tier), 'kanji,', len(info), 'of', len(keys), 'words matched,', len(gram), 'grammar points')
print('unmatched:', ' '.join(k for k in keys if k not in info))
