// Merged into sports only. Global club entries call these local scene nodes.
export const tennisNodes = {
  d4_rei_name: [{ if: '!d4_rei_intro', then: [
    { say: 'rei', emo: 'casual', text: 'I’m Rei. Are you here to play, or about the display?' },
    { say: 'eric', emo: 'warm', text: 'I’m {mc.name}, from B2. I thought I’d have a look.' },
    { do: 'meet', who: 'rei' }, { set: 'd4_rei_intro' }, { do: 'save' },
  ] }],
  d4_aoi_name: [{ if: '!d3_aoi_intro', then: [
    { say: 'aoi', overheard: true, emo: 'polite', text: 'あ、電車で会いましたよね。アオイです。', clear: ['アオイ'] },
    { do: 'gesture', who: 'aoi', kind: 'point', to: 'aoi' },
    { say: 'eric', emo: 'warm', text: 'I remember you. I’m {mc.name}.' },
    { do: 'meet', who: 'aoi' }, { set: 'd3_aoi_intro' }, { do: 'save' },
  ] }],
  d4_tennis_offer: [
    { if: "period != 'evening' || !club_tennis", then: [{ end: true }] },
    { if: 'd4_tennis_done', then: [{ go: 'd4_tennis_repeat' }] },
    { do: 'tennisSession', state: 'begin' },
    { call: 'd4_rei_name' }, { call: 'd4_aoi_name' },
    { if: 'know_yoyaku', then: [
      { say: 'eric', emo: 'curious', text: 'Do we have a {yoyaku} for this court?' },
      { say: 'rei', name: 'Rei', emo: 'casual', text: 'Yes, until they finish their game. Have you brought a racket?' },
    ], else: [{ say: 'rei', name: 'Rei', emo: 'casual', text: 'We’ve got the practice court until they finish. Have you brought a racket?' }] },
    { do: 'tennisSession', state: 'racket' },
    { say: 'aoi', name: 'Aoi', overheard: true, emo: 'hesitant', text: '私も、ラケットを借りていいですか。', clear: ['ラケット'] },
    { say: 'rei', name: 'Rei', emo: 'warm', text: 'You can both borrow one. Aoi, you can put the basket down.' },
    { do: 'gesture', who: 'rei', kind: 'point', to: 'ball_basket' },
    { do: 'tennisSession', state: 'basketDown' },
    { do: 'gesture', who: 'aoi', kind: 'beckon', to: 'eric' },
    { say: 'aoi', name: 'Aoi', overheard: true, emo: 'polite', text: '{isshoni}、やりませんか。' },
    { say: 'rei', name: 'Rei', emo: 'casual', text: 'She’s asking you to play with her. You can have a go together.' },
    { if: '!know_isshoni', then: [{ choice: [
      { text: 'Ask which word means “together”.', go: 'd4_together' },
      { text: 'Take a racket.', go: 'd4_tennis_choose' },
      { text: 'Come back to tennis later.', go: 'd4_tennis_leave' },
    ] }], else: [{ go: 'd4_tennis_choose' }] },
  ],
  d4_together: [
    { say: 'eric', emo: 'curious', text: 'Which bit was “together”?' },
    { say: 'aoi', name: 'Aoi', emo: 'slow', slow: true, text: '{isshoni}。' },
    { do: 'type', word: 'isshoni', from: 'aoi', prompt: 'Try Aoi’s word for “together”: isshoni.' },
    { go: 'd4_tennis_choose' },
  ],
  d4_tennis_choose: [{ choice: [
    { text: 'Practise with Aoi.', go: 'd4_aoi_rally' },
    { text: 'Ask Rei to demonstrate a serve.', go: 'd4_rei_serve' },
    { text: 'Try saying “I’d like to go together”.', if: 'know_isshoni && know_ikitai && !d4_invitation_said', go: 'd4_tennis_invite' },
    { text: 'Come back to tennis later.', go: 'd4_tennis_leave' },
  ] }],
  d4_tennis_invite: [
    { say: 'eric', emo: 'hesitant', text: '{isshoni}... {ikitai}.' },
    { do: 'gesture', who: 'aoi', kind: 'beckon', to: 'eric' },
    { say: 'aoi', name: 'Aoi', overheard: true, emo: 'warm', text: 'はい、あっちに行きましょう。' },
    { say: 'rei', name: 'Rei', emo: 'casual', text: 'You want to go over together? Yes, that court is free.' },
    { set: 'd4_invitation_said' }, { go: 'd4_tennis_choose' },
  ],
  d4_aoi_rally: [
    { set: 'd4_played_aoi' }, { do: 'tennisSession', state: 'aoiRally' },
    { say: 'aoi', name: 'Aoi', overheard: true, emo: 'sheepish', text: 'あ、下を通っちゃった。取ってきます。' },
    { do: 'tennisSession', state: 'fetch' },
    { say: 'eric', emo: 'warm', text: 'Let me stand a bit closer this time.' },
    { do: 'gesture', who: 'aoi', kind: 'nod', to: 'eric' },
    { say: 'aoi', name: 'Aoi', overheard: true, emo: 'warm', text: 'もう一回、お願いします。' },
    { do: 'tennisSession', state: 'aoiAgain' }, { go: 'd4_tennis_finish' },
  ],
  d4_rei_serve: [
    { set: 'd4_watched_rei' },
    { say: 'rei', name: 'Rei', emo: 'casual', text: 'Turn sideways first. Then bring the racket back, and when you toss the ball...' },
    { say: 'eric', emo: 'hesitant', text: 'Hang on, where should my feet be?' },
    { say: 'rei', name: 'Rei', emo: 'sheepish', text: 'Sorry, I’m getting ahead. Watch my feet for this one.' },
    { do: 'tennisSession', state: 'serve' },
    { do: 'gesture', who: 'aoi', kind: 'point', to: 'rei' },
    { say: 'aoi', name: 'Aoi', overheard: true, emo: 'curious', text: '私も、やってみていいですか。' },
    { say: 'rei', name: 'Rei', emo: 'warm', text: 'Your turn, Aoi. I’ll move back.' },
    { do: 'tennisSession', state: 'aoiTurn' }, { go: 'd4_tennis_finish' },
  ],
  d4_tennis_finish: [
    { set: 'd4_tennis_done' },
    { say: 'rei', name: 'Rei', emo: 'casual', text: 'They’ve finished. I’m going over for doubles. Keep the spare, Aoi, I’ve got mine.' },
    { do: 'tennisSession', state: 'doubles' },
    { do: 'gesture', who: 'aoi', kind: 'point', to: 'bench_ball' },
    { say: 'aoi', name: 'Aoi', overheard: true, emo: 'warm', text: 'ちょっと、休みませんか。' },
    { say: 'eric', emo: 'curious', text: 'Shall we sit down for a bit?' },
    { do: 'gesture', who: 'aoi', kind: 'nod' },
    { do: 'save' },
    { choice: [{ text: 'Stay for a drink.', go: 'd4_tennis_drink' }, { text: 'Head out.', go: 'd4_tennis_leave' }] },
  ],
  d4_tennis_drink: [
    { do: 'tennisSession', state: 'drink' },
    { do: 'tennisSession', state: 'shoe' },
    { say: 'aoi', name: 'Aoi', overheard: true, emo: 'sheepish', text: '店では、ちょうどよかったんですけど。' },
    { say: 'eric', emo: 'curious', text: 'Are they pinching? Mine do that after a while.' },
    { do: 'gesture', who: 'aoi', kind: 'nod' },
    { say: 'aoi', name: 'Aoi', overheard: true, emo: 'warm', text: 'でも、来週も来ます。' },
    { say: 'eric', emo: 'warm', text: 'I’m glad you came over to play.' },
    { go: 'd4_tennis_leave' },
  ],
  d4_tennis_leave: [{ do: 'tennisSession', state: 'free' }, { do: 'cam', back: true }, { do: 'save' }],
  d4_tennis_repeat: [
    { say: 'rei', name: 'Rei', emo: 'warm', text: 'We can fit you in after this game. Aoi’s over there if you want to warm up.' },
    { choice: [{ text: 'Hit a few balls with Aoi.', go: 'd4_tennis_repeat_play' }, { text: 'Watch from the bench.', go: 'd4_tennis_leave' }] },
  ],
  d4_tennis_repeat_play: [{ do: 'tennisSession', state: 'repeat' }, { go: 'd4_tennis_leave' }],
};
