import { direction, sayFallbacks, fallbackNodes } from './shared.js';
export default {
  start: 'd2_arrive',
  speakers: { kuro: { name: 'Receptionist' } },
  labels: { kuro: 'Receptionist' },
  on: {
    'talk:campus':'to_campus','zone:campus_exit':'to_campus',
    'talk:shop_lane': 'd2_to_shotengai', 'zone:shop_exit': 'd2_to_shotengai',
    'talk:kuro': [{ if: "period == 'evening' && know_watashi && !d2_kuro_evening_seen", node: 'd2_kuro_evening' }, 'd2_kuro_talk'],
    'say:ohayo:kuro': 'd2_kuro_greet',
    'say:daijoubu:kuro': 'd2_kuro_ok',
    'talk:station_exit': 'd2_to_station', 'zone:station_exit': 'd2_to_station',
    'talk:office_entrance': 'd2_to_office', 'zone:lift_front': 'd2_to_office',
    'talk:plaza_lane': 'd2_to_plaza', 'zone:plaza_lane': 'd2_to_plaza',
    ...sayFallbacks,
  },
  nodes: {
    to_campus:[{do:'trip',to:'campus'}],
    d2_to_shotengai: [{ do: 'trip', to: 'shotengai' }],
    d2_kuro_talk: [
      { do: 'face', who: 'kuro', to: 'eric' },
      { do: 'cam', on: 'kuro', zoom: 1.2 },
      { if: 'd2_kuro_work_seen && d2_kuro_weekend_seen', then: [
        { say: 'kuro', overheard: true, emo: 'polite', text: '電話です。また、あとで。' },
        { go: 'd2_kuro_end' },
      ], else: [{ go: 'd2_kuro_topics' }] },
    ],
    d2_kuro_topics: [{ choice: [
      { text: '{ohayo}. Good morning.', if: 'know_ohayo && !d2_kuro_greeted', go: 'd2_kuro_greet' },
      { text: 'Do you work here every day?', if: '!d2_kuro_work_seen', go: 'd2_kuro_work' },
      { text: 'What do you do on your days off?', if: '!d2_kuro_weekend_seen', go: 'd2_kuro_weekend' },
      { text: '{daijoubu}. I found my way today.', if: 'know_daijoubu && !d2_kuro_ok_seen', go: 'd2_kuro_ok' },
      { text: 'I’ll let you get back to work.', go: 'd2_kuro_end' },
    ] }],
    d2_kuro_greet: [
      { say: 'eric', emo: 'polite', text: '{ohayo}.' },
      { say: 'kuro', voice: 'kuro-ohayo', overheard: true, emo: 'warm', text: '{ohayo}。' },
      { say: 'kuro', overheard: true, emo: 'warm', text: '覚えてたんですね。' },
      { set: 'd2_kuro_greeted' }, { go: 'd2_kuro_topics' },
    ],
    d2_kuro_work: [
      { say: 'kuro', overheard: true, emo: 'casual', text: '明日は{watashi}、{yasumi}です。' },
      '> She points at herself as she says it.',
      { say: 'kuro', emo: 'slow', slow: true, text: '{yasumi}。' },
      { do: 'type', word: 'yasumi', from: 'kuro', prompt: 'She has tomorrow off. Try yasumi: a break or day off.' },
      { say: 'eric', emo: 'warm', text: 'Mine too. I’m still working out what’s here.' },
      { if: '!know_watashi', then: [
        { say: 'kuro', emo: 'slow', slow: true, text: '{watashi}。' },
        { do: 'type', word: 'watashi', from: 'kuro', prompt: 'She points at herself again. Try watashi: I, me.' },
        { say: 'kuro', overheard: true, emo: 'warm', text: 'はい、{watashi}。' },
      ] },
      { set: 'd2_kuro_work_seen' }, { go: 'd2_kuro_topics' },
    ],
    d2_kuro_weekend: [
      { if: 'know_yasumi', then: [{ say: 'eric', emo: 'curious', text: '{yasumi}... What do you do then?' }], else: [{ say: 'eric', emo: 'curious', text: 'What do you do when you’re off work?' }] },
      { say: 'kuro', overheard: true, emo: 'casual', text: 'プール、行きます。泳げますか？', clear: [{ ja: 'プール', ro: 'pūru', en: 'pool' }] },
      { do: 'gesture', who: 'kuro', kind: 'point', to: 'eric' },
      { choice: [
        { text: 'Yes. I haven’t been for a while.', go: 'd2_kuro_swimmer' },
        { text: 'A little. I’d have to start slowly.', go: 'd2_kuro_beginner' },
      ] },
    ],
    d2_kuro_swimmer: [
      { say: 'kuro', overheard: true, emo: 'warm', text: 'じゃあ、クラブで。', clear: [{ ja: 'クラブ', ro: 'kurabu', en: 'club' }] },
      { do: 'gesture', who: 'kuro', kind: 'point', to: 'plaza_lane' },
      { set: 'd2_kuro_weekend_seen' }, { go: 'd2_kuro_topics' },
    ],
    d2_kuro_beginner: [
      { say: 'kuro', overheard: true, emo: 'warm', text: 'ゆっくりで、いいですよ。クラブで。', clear: [{ ja: 'クラブ', ro: 'kurabu', en: 'club' }] },
      { do: 'gesture', who: 'kuro', kind: 'point', to: 'plaza_lane' },
      { set: 'd2_kuro_weekend_seen' }, { go: 'd2_kuro_topics' },
    ],
    d2_kuro_ok: [
      { say: 'eric', emo: 'warm', text: '{daijoubu}. I found the right lift today.' },
      { say: 'kuro', overheard: true, emo: 'teasing', text: 'じゃあ、話しに来ただけ？' },
      { say: 'eric', emo: 'warm', text: 'I did, yes.' },
      { set: 'd2_kuro_ok_seen' }, { go: 'd2_kuro_topics' },
    ],
    d2_kuro_evening: [
      { do: 'face', who: 'kuro', to: 'eric' },
      { do: 'cam', on: 'kuro', zoom: 1.3 },
      { say: 'kuro', voice: 'kuro-otsukare', overheard: true, emo: 'polite', text: 'お疲れさまです。' },
      { choice: [
        { text: '“Good evening. It’s been a long day.”', go: 'd2_kuro_eve_english' },
        { text: 'Say {otsukare} back.', go: 'd2_kuro_eve_effort' },
      ] },
    ],
    d2_kuro_eve_english: [
      { say: 'eric', emo: 'tired', text: 'Good evening. It’s been a long day.' },
      { say: 'kuro', emo: 'polite', text: 'Good evening.' },
      { do: 'gesture', who: 'kuro', kind: 'nod', to: 'eric' },
      { set: 'd2_kuro_evening_seen' }, { go: 'd2_kuro_end' },
    ],
    d2_kuro_eve_effort: [
      { say: 'eric', emo: 'tired', text: '{otsukare}.' },
      { say: 'kuro', overheard: true, emo: 'warm', text: 'はい、お疲れさまです。……その袖、どうしたんですか。' },
      '> She leans over the counter and brushes the dust off your sleeve without asking.',
      { say: 'eric', emo: 'casual', text: 'Machine room dust. It doesn’t come off.' },
      { say: 'kuro', overheard: true, emo: 'amused', text: '落ちませんね。' },
      { say: 'kuro', overheard: true, emo: 'casual', text: '{watashi}は、明日{yasumi}。' },
      { say: 'kuro', emo: 'slow', slow: true, text: '{anata}。' },
      '> She taps your chest with one finger and waits.',
      { say: 'kuro', overheard: true, emo: 'curious', text: '{anata}は？' },
      { do: 'type', word: 'anata', from: 'kuro', prompt: 'She’s pointing at you. Try “you”: anata.' },
      { say: 'eric', emo: 'warm', text: '...I mean, me too. I’m off tomorrow.' },
      { say: 'kuro', overheard: true, emo: 'amused', text: '「{anata}」じゃなくて、「{watashi}」。でも、上手。' },
      { set: 'kuro_tried_japanese' }, { set: 'd2_kuro_evening_seen' }, { go: 'd2_kuro_end' },
    ],
    d2_kuro_end: [{ do: 'cam', back: true }, { do: 'save' }],
    d2_arrive: direction('station_exit', 'office_entrance', 'plaza_lane', 'plaza_lane'),
    d2_to_station: [{ do: 'trip', to: 'gate' }],
    d2_to_office: [{ do: 'trip', to: 'office' }],
    d2_to_plaza: [{ do: 'trip', to: 'plaza' }],
    ...fallbackNodes,
  },
};
