// Shared runtime declaration; tooling imports this without DOM or renderer side effects.
export const DEFAULT_SPEAKERS = {
  eric: { name: 'Eric', role: 'you', color: '#8fb4d8' },
  mio: { name: 'Mio', role: 'programmer', color: '#5fc6bf' },
  aoi: { name: 'Aoi', color: '#e79fb0' },
  kuroda: { name: 'Mr. Hamada', role: 'Accounts', color: '#b3a58f' },
  guard: { name: 'Mr. Ishibashi', role: 'security', color: '#8ea2c8' },
  kuro: { name: 'Kuro', role: 'reception', color: '#c3a7d6' },
  emi: { name: 'Emi', color: '#e0906f' },
  mori: { name: 'Mr. Mori', role: 'section chief', color: '#b9a3d3' },
  kenji: { name: 'Kenji', color: '#9fb6d8' },
  yui: { name: 'Yui', color: '#d7b27e' },
  sota: { name: 'Sota', color: '#9cc39a' },
  nao: { name: 'Nao', color: '#a9c3c0' },
  hiro: { name: 'Hiro', color: '#c0b39f' },
  ann: { name: 'Announcement', color: '#9aa9bd' },
  reader: { name: 'Man with a book', color: '#a8b0bf' },
  music: { name: 'Girl with headphones', color: '#a8b0bf' },
  bun: { name: 'Woman with a bun', color: '#a8b0bf' },
  youth: { name: 'Young man', color: '#a8b0bf' },
  stander: { name: 'Man by the door', color: '#a8b0bf' },
  commuter: { name: 'Office worker', color: '#a8b0bf' },
  rei: { name: 'Rei', role: 'Sales', color: '#c9ced8' },
  kanae: { name: 'Kanae', color: '#f0a060' },
  sales1: { name: 'Man from Sales', color: '#a8b0bf' },
  sales2: { name: 'Woman from Sales', color: '#a8b0bf' },
  gatev: { name: 'Gate', role: 'recorded voice', color: '#7fd0c8' },
  reitext: { name: 'Rei', role: 'message', color: '#c9ced8', phone: true },
};
