// Story half of #230. The minigame bridge must return through these nodes; see README.
export const revealNodes = {
  d5_drinks: [
    { if: "period != 'evening'", then: [{ say: 'eric', emo: 'casual', text: 'Mio’s message said drinks here after six. I’ll come back then.' }, { end: true }] },
    { call: 'd5_kenji_name' }, { call: 'd5_mori_name' },
    { if: 'd5_team_witnessed', then: [{ go: 'd5_drinks_again' }] },
    { if: 'd5_delivery_seen', then: [{ go: 'd5_first_reactions' }] },
    { do: 'teamDrinks', state: 'gather' },
    { say: 'kenji', emo: 'bright', text: 'I want melon soda. Mori-san, coffee?' },
    { say: 'mori', overheard: true, emo: 'polite', text: '今日は、お茶をお願いします。' },
    { say: 'mio', emo: 'casual', text: 'He wants tea. I’ll have coffee, if you’re buying.' },
    { say: 'eric', emo: 'hesitant', text: 'Kenji, I think I can get yours over to you without touching the machine.' },
    { say: 'kenji', emo: 'puzzled', text: 'You have remote?' },
    { do: 'teamDrinks', state: 'aside' },
    { say: 'mio', emo: 'low', text: 'You mean with a word? You want them to see?' },
    { choice: [
      { text: 'Yes, if they want to.', go: 'd5_reveal_agree' },
      { text: 'Let’s just have ordinary drinks tonight.', go: 'd5_reveal_defer' },
    ] },
  ],
  d5_reveal_agree: [
    { do: 'teamDrinks', state: 'private' },
    { say: 'mio', emo: 'low', text: 'Okay, everyone else has gone. Kenji, put your phone away first, please.' },
    { do: 'teamDrinks', state: 'phoneAway' },
    { say: 'kenji', emo: 'puzzled', text: 'Okay. What is it?' },
    { say: 'mio', emo: 'hesitant', text: 'I’ve seen {mc.them} move things by speaking to them. I don’t know how. Do you want to see?' },
    { say: 'kenji', emo: 'curious', text: 'Yes. Can you do it with my drink?' },
    { do: 'face', who: 'mio', to: 'mori' }, { do: 'cam', on: 'mori', zoom: 2.2 },
    { say: 'mio', overheard: true, emo: 'hesitant', text: '森さん、言葉だけで物が動くんです。見てみますか。', clear: ['森'] },
    { say: 'mori', overheard: true, emo: 'curious', text: '言葉で？ええ、見せてください。' },
    { do: 'gesture', who: 'mori', kind: 'nod', to: 'eric' },
    { do: 'teamDrinks', state: 'clear' },
    { say: 'mio', emo: 'casual', text: 'He’d like to see too. You’ve got room now.' },
    { set: 'd5_reveal_agreed' }, { do: 'save' }, { go: 'd5_delivery_prepare' },
  ],
  d5_delivery_prepare: [
    { if: '!know_dashite', then: [{ call: 'd5_printer_lesson' }] },
    { say: 'mio', emo: 'casual', text: 'Do Kenji’s melon soda first. He’s been looking at that machine since six.' },
    { do: 'teamDrinks', state: 'guidedDelivery' },
  ],
  d5_first_reactions: [
    { if: "!d5_delivery_seen || period != 'evening'", then: [{ end: true }] },
    { if: 'd5_team_witnessed', then: [{ go: 'd5_drinks_again' }] },
    { do: 'teamDrinks', state: 'deliveryPose' },
    { say: 'kenji', emo: 'surprised', text: 'I didn’t press it! How did you... it’s cold.' },
    { if: 'd5_selector_magic', then: [
      { say: 'kenji', emo: 'puzzled', text: 'You did this at karaoke? When you said stop?' },
      { say: 'eric', emo: 'hesitant', text: 'Yes, I think it’s the same thing.' },
    ] },
    { do: 'look', who: 'mori', at: 'eric' },
    { say: 'mori', overheard: true, emo: 'puzzled', text: '本当に、何も触っていませんね……。' },
    { say: 'mio', emo: 'low', text: 'He says you didn’t touch anything. I know, Mori-san... I’ve seen it like five times now and I still don’t get it.' },
    { say: 'mio', emo: 'low', text: 'Can this stay in B2? If upstairs hears about it, it goes on some list, and then it’s my list.' },
    { say: 'kenji', emo: 'low', text: 'Okay. I won’t tell them.' },
    { do: 'face', who: 'mio', to: 'mori' }, { do: 'cam', on: 'mori', zoom: 2.2 },
    { say: 'mio', overheard: true, emo: 'low', text: '森さん、このことは、まだ他の人に話さないでください。', clear: ['森'] },
    { say: 'mori', overheard: true, emo: 'polite', text: 'ええ、ここだけの話にしましょう。' },
    { do: 'gesture', who: 'mori', kind: 'nod', to: 'eric' },
    { say: 'mio', emo: 'warm', text: 'He won’t tell anyone either.' },
    { set: 'd5_team_witnessed' }, { unset: 'd5_reveal_agreed' }, { do: 'save' },
    { choice: [{ text: 'Try a few more deliveries.', go: 'd5_drinks_continue' }, { text: 'Finish with that first drink.', go: 'd5_first_exit' }] },
  ],
  d5_reveal_defer: [
    { say: 'mio', emo: 'casual', text: 'Sure. Come on, Kenji’s waiting for us.' },
    { do: 'teamDrinks', state: 'ordinary' },
    { say: 'kenji', emo: 'warm', text: '{mc.name}, what do you want?' },
    { say: 'eric', emo: 'warm', text: 'Water for me. Thanks.' },
    { do: 'teamDrinks', state: 'ordinaryServe' }, { go: 'd5_drinks_free' },
  ],
  d5_drinks_again: [
    { do: 'teamDrinks', state: 'gather' },
    { say: 'kenji', emo: 'curious', text: 'Can we try again? I want to watch from here.' },
    { choice: [{ text: 'Try a few deliveries.', go: 'd5_drinks_continue' }, { text: 'Have an ordinary drink.', go: 'd5_replay_ordinary' }, { text: 'Head out.', go: 'd5_drinks_free' }] },
  ],
  d5_replay_ordinary: [{ do: 'teamDrinks', state: 'ordinaryServe' }, { say: 'kenji', emo: 'warm', text: 'Okay, I’ll get them.' }, { go: 'd5_drinks_free' }],
  d5_drinks_continue: [{ if: "d5_team_witnessed && period == 'evening'", then: [{ do: 'teamDrinks', state: 'continue' }] }],
  d5_first_exit: [
    { say: 'kenji', emo: 'warm', text: 'Thank you. I forgot I wanted to drink it.' }, { go: 'd5_drinks_free' },
  ],
  d5_rounds_exit: [
    { if: "d5_last_recipient == 'kenji'", then: [{ say: 'kenji', emo: 'warm', text: 'Thank you. I have enough now.' }] },
    { if: "d5_last_recipient == 'mori'", then: [{ say: 'mori', overheard: true, emo: 'polite', text: 'ありがとうございます。ゆっくり、いただきます。' }, { do: 'bow', who: 'mori' }] },
    { if: "d5_last_recipient == 'mio'", then: [{ say: 'mio', emo: 'casual', text: 'Thanks. I’ll finish this before I go.' }] },
    { go: 'd5_drinks_free' },
  ],
  d5_delivery_cancel: [{ unset: 'd5_reveal_agreed' }, { say: 'mio', emo: 'casual', text: 'We can leave it for tonight.' }, { go: 'd5_drinks_free' }],
  d5_drinks_free: [
    { do: 'teamDrinks', state: 'free' }, { do: 'cam', back: true },
    { if: 'd5_team_witnessed', then: [{ set: 'd5_reveal_done' }] }, { do: 'save' },
  ],
  d5_printer_lesson: [
    { say: 'mio', emo: 'casual', text: 'Try the printer word first. I’ll ask Mori-san to show you.' },
    { say: 'mio', overheard: true, emo: 'casual', text: '森さん、依頼書を一枚、出してもらえますか。', clear: ['森'] },
    { say: 'mori', overheard: true, emo: 'polite', text: 'はい。{dashite}……と。' },
    { do: 'teamDrinks', state: 'printLesson' },
    { say: 'mio', emo: 'casual', text: 'He said {dashite}, like “give it out”. The sheet’s done already, so you can try it without printing forty more.' },
    { say: 'mori', emo: 'slow', slow: true, text: '{dashite}。' },
    { do: 'type', word: 'dashite', from: 'mori', prompt: 'Practise after the completed print: dashite.' }, { do: 'save' },
  ],
};
