// Dictionary for the mechanics prototypes: key (dictionary form) -> reading and meaning.
export const LEX = {
  // time, days, numbers
  '今日': { r: 'きょう', en: 'today' }, '明日': { r: 'あした', en: 'tomorrow' }, '昨日': { r: 'きのう', en: 'yesterday' },
  '今': { r: 'いま', en: 'now' }, '朝': { r: 'あさ', en: 'morning' }, '昼': { r: 'ひる', en: 'noon, midday' }, 'お昼': { r: 'おひる', en: 'lunch, lunchtime' },
  '午後': { r: 'ごご', en: 'afternoon, p.m.' }, '週末': { r: 'しゅうまつ', en: 'weekend' }, '先週': { r: 'せんしゅう', en: 'last week' },
  '時間': { r: 'じかん', en: 'time' }, '何時': { r: 'なんじ', en: 'what time' }, '十分後': { r: 'じゅっぷんご', en: 'ten minutes later, in ten minutes' },
  '月曜日': { r: 'げつようび', en: 'Monday' }, '火曜日': { r: 'かようび', en: 'Tuesday' }, '水曜日': { r: 'すいようび', en: 'Wednesday' }, '木曜日': { r: 'もくようび', en: 'Thursday' },
  '金曜日': { r: 'きんようび', en: 'Friday' }, '土曜日': { r: 'どようび', en: 'Saturday' }, '日曜日': { r: 'にちようび', en: 'Sunday' },
  '一時': { r: 'いちじ', en: "one o'clock" }, '二時': { r: 'にじ', en: "two o'clock" }, '三時': { r: 'さんじ', en: "three o'clock" }, '四時': { r: 'よじ', en: "four o'clock" },
  '五時': { r: 'ごじ', en: "five o'clock" }, '六時': { r: 'ろくじ', en: "six o'clock" }, '九時': { r: 'くじ', en: "nine o'clock" }, '十時': { r: 'じゅうじ', en: "ten o'clock" },
  '十一時': { r: 'じゅういちじ', en: "eleven o'clock" }, '十二時': { r: 'じゅうにじ', en: "twelve o'clock" },
  '一時半': { r: 'いちじはん', en: 'half past one' }, '二時半': { r: 'にじはん', en: 'half past two' }, '三時半': { r: 'さんじはん', en: 'half past three' }, '四時半': { r: 'よじはん', en: 'half past four' },
  '五時半': { r: 'ごじはん', en: 'half past five' }, '九時半': { r: 'くじはん', en: 'half past nine' }, '十時半': { r: 'じゅうじはん', en: 'half past ten' }, '十一時半': { r: 'じゅういちじはん', en: 'half past eleven' },
  '一部': { r: 'いちぶ', en: 'one copy' }, '二部': { r: 'にぶ', en: 'two copies' }, '三部': { r: 'さんぶ', en: 'three copies' }, '四部': { r: 'よんぶ', en: 'four copies' }, '五部': { r: 'ごぶ', en: 'five copies' },
  '六部': { r: 'ろくぶ', en: 'six copies' }, '七部': { r: 'ななぶ', en: 'seven copies' }, '八部': { r: 'はちぶ', en: 'eight copies' }, '十部': { r: 'じゅうぶ', en: 'ten copies' },
  '一枚': { r: 'いちまい', en: 'one sheet (flat things)' }, '二枚': { r: 'にまい', en: 'two sheets' }, '三枚': { r: 'さんまい', en: 'three sheets' }, '四枚': { r: 'よんまい', en: 'four sheets' },
  '五枚': { r: 'ごまい', en: 'five sheets' }, '七枚': { r: 'ななまい', en: 'seven sheets' }, '八枚': { r: 'はちまい', en: 'eight sheets' }, '十枚': { r: 'じゅうまい', en: 'ten sheets' }, '百枚': { r: 'ひゃくまい', en: 'a hundred sheets' },
  '一つ': { r: 'ひとつ', en: 'one (thing)' }, '二つ': { r: 'ふたつ', en: 'two (things)' }, '三つ': { r: 'みっつ', en: 'three (things)' }, '四つ': { r: 'よっつ', en: 'four (things)' },
  '五つ': { r: 'いつつ', en: 'five (things)' }, '六つ': { r: 'むっつ', en: 'six (things)' }, '七つ': { r: 'ななつ', en: 'seven (things)' }, '八つ': { r: 'やっつ', en: 'eight (things)' },
  '一人': { r: 'ひとり', en: 'one person, alone' }, '二人': { r: 'ふたり', en: 'two people' }, '三人': { r: 'さんにん', en: 'three people' }, '四人': { r: 'よにん', en: 'four people' },
  '五人': { r: 'ごにん', en: 'five people' }, '六人': { r: 'ろくにん', en: 'six people' }, '八人': { r: 'はちにん', en: 'eight people' },
  '一杯': { r: 'いっぱい', en: 'one glass, one drink' },
  // places and directions
  '一階': { r: 'いっかい', en: 'first floor, ground floor' }, '二階': { r: 'にかい', en: 'second floor' }, '三階': { r: 'さんがい', en: 'third floor' }, '四階': { r: 'よんかい', en: 'fourth floor' },
  '五階': { r: 'ごかい', en: 'fifth floor' }, '地下': { r: 'ちか', en: 'basement, underground' }, '地下一階': { r: 'ちかいっかい', en: 'basement level 1' }, '地下二階': { r: 'ちかにかい', en: 'basement level 2' },
  '右': { r: 'みぎ', en: 'right' }, '左': { r: 'ひだり', en: 'left' }, '右側': { r: 'みぎがわ', en: 'right side' }, '後ろ': { r: 'うしろ', en: 'behind, back' }, '奥': { r: 'おく', en: 'the back, the far end' },
  '先': { r: 'さき', en: 'ahead, first' }, '出口': { r: 'でぐち', en: 'exit' }, '駅': { r: 'えき', en: 'station' }, '中央駅': { r: 'ちゅうおうえき', en: 'central station' },
  '部屋': { r: 'へや', en: 'room' }, '会議室': { r: 'かいぎしつ', en: 'meeting room' }, '倉庫': { r: 'そうこ', en: 'storeroom' }, '役員室': { r: 'やくいんしつ', en: 'executive office' },
  '市場': { r: 'いちば', en: 'market' }, '席': { r: 'せき', en: 'seat' }, '天川': { r: 'あまかわ', en: 'Amakawa (the company)' }, '営業部': { r: 'えいぎょうぶ', en: 'sales department' },
  // people
  '人': { r: 'ひと', en: 'person' }, '私': { r: 'わたし', en: 'I, me' }, '誰': { r: 'だれ', en: 'who' }, '新人': { r: 'しんじん', en: 'new hire, newcomer' },
  '部長': { r: 'ぶちょう', en: 'department head' }, '課長': { r: 'かちょう', en: 'section chief' }, '先輩': { r: 'せんぱい', en: 'senior colleague (senpai)' }, '店員': { r: 'てんいん', en: 'shop staff' },
  '同い年': { r: 'おないどし', en: 'the same age' }, '田中': { r: 'たなか', en: 'Tanaka (a family name)' }, '黒田': { r: 'くろだ', en: 'Kuroda (a family name)' }, '様': { r: 'さま', en: 'polite Mr/Ms (どちら様 = who, very polite)' },
  'アオイ': { en: 'Aoi (a name)' },
  // things
  '水': { r: 'みず', en: 'water' }, '本': { r: 'ほん', en: 'book' }, '犬': { r: 'いぬ', en: 'dog' }, '雨': { r: 'あめ', en: 'rain' }, '傘': { r: 'かさ', en: 'umbrella' }, '鍵': { r: 'かぎ', en: 'key' },
  '窓': { r: 'まど', en: 'window' }, '電車': { r: 'でんしゃ', en: 'train' }, '電話': { r: 'でんわ', en: 'phone, phone call' }, '映画': { r: 'えいが', en: 'film, movie' }, '名前': { r: 'なまえ', en: 'name' },
  '会議': { r: 'かいぎ', en: 'meeting' }, '資料': { r: 'しりょう', en: 'papers, handouts, materials' }, '書類': { r: 'しょるい', en: 'documents' }, '印刷': { r: 'いんさつ', en: 'printing' },
  '締め切り': { r: 'しめきり', en: 'deadline' }, '荷物': { r: 'にもつ', en: 'package, luggage' }, '紙': { r: 'かみ', en: 'paper' }, '椅子': { r: 'いす', en: 'chair' },
  '財布': { r: 'さいふ', en: 'wallet' }, '封筒': { r: 'ふうとう', en: 'envelope' }, '携帯': { r: 'けいたい', en: 'mobile phone' }, '鞄': { r: 'かばん', en: 'bag' }, '袋': { r: 'ふくろ', en: 'bag (shopping bag)' },
  '服': { r: 'ふく', en: 'clothes' }, '社員証': { r: 'しゃいんしょう', en: 'staff ID card' }, '写真': { r: 'しゃしん', en: 'photo' }, '缶': { r: 'かん', en: 'can (tin)' }, '機': { r: 'き', en: 'machine (コピー機 = copier)' },
  '顔': { r: 'かお', en: 'face' }, '頭': { r: 'あたま', en: 'head' }, 'お腹': { r: 'おなか', en: 'stomach, belly' }, '話': { r: 'はなし', en: 'talk, story, what we\'re talking about' },
  '連絡': { r: 'れんらく', en: 'contact, getting in touch (連絡する = let someone know)' }, '営業': { r: 'えいぎょう', en: 'sales' }, '敬語': { r: 'けいご', en: 'polite language (keigo)' },
  '礼': { r: 'れい', en: 'thanks (お礼 = a thank-you)' }, '乾杯': { r: 'かんぱい', en: 'cheers! (a toast)' }, '言い方': { r: 'いいかた', en: 'way of saying it' }, '早退': { r: 'そうたい', en: 'leaving work early' },
  'はさみ': { en: 'scissors' },
  // adjectives and adverbs
  '大きい': { r: 'おおきい', en: 'big' }, '新しい': { r: 'あたらしい', en: 'new' }, '寒い': { r: 'さむい', en: 'cold (weather, room)' }, '強い': { r: 'つよい', en: 'strong' }, '早め': { r: 'はやめ', en: 'a bit early (早めに = early)' }, '前': { r: 'まえ', en: 'before, in front' }, '電気': { r: 'でんき', en: 'electricity, the lights' }, '消す': { r: 'けす', en: 'to turn off' }, '忙しい': { r: 'いそがしい', en: 'busy' },
  '悪い': { r: 'わるい', en: 'bad (悪いね = sorry)' }, '怖い': { r: 'こわい', en: 'scary' }, '痛い': { r: 'いたい', en: 'painful, hurts' }, '早い': { r: 'はやい', en: 'early, fast' },
  '本当': { r: 'ほんとう', en: 'true, real' }, '静か': { r: 'しずか', en: 'quiet' }, '一緒': { r: 'いっしょ', en: 'together' }, '元気': { r: 'げんき', en: 'lively, well' }, '無理': { r: 'むり', en: 'impossible, too much' },
  '大丈夫': { r: 'だいじょうぶ', en: 'fine, OK (also: no thanks)' }, '丁寧': { r: 'ていねい', en: 'polite, careful' }, '少し': { r: 'すこし', en: 'a little' }, '少々': { r: 'しょうしょう', en: 'a moment (polite)' },
  '好き': { r: 'すき', en: 'like, fond of' }, '休み': { r: 'やすみ', en: 'day off, break' }, '急': { r: 'きゅう', en: 'sudden (急に = suddenly)' }, '次': { r: 'つぎ', en: 'next' }, '何': { r: 'なに', en: 'what (なに, or なん before some sounds)' }, '中': { r: 'ちゅう', en: 'in the middle of (doing)' },
  '赤': { r: 'あか', en: 'red' }, '青': { r: 'あお', en: 'blue' }, '白': { r: 'しろ', en: 'white' }, '黒': { r: 'くろ', en: 'black' }, '黄色': { r: 'きいろ', en: 'yellow' }, '緑': { r: 'みどり', en: 'green' },
  'ちょっと': { en: 'a little, a moment' }, 'もう': { en: 'already, (any) more' }, 'ここ': { en: 'here' },
  // verbs
  '来る': { r: 'くる', en: 'to come' }, '参る': { r: 'まいる', en: 'to come, to go (humble)' }, '行く': { r: 'いく', en: 'to go' }, '帰る': { r: 'かえる', en: 'to go home' }, '待つ': { r: 'まつ', en: 'to wait' }, '見る': { r: 'みる', en: 'to look, to see' },
  '見せる': { r: 'みせる', en: 'to show' }, '飲む': { r: 'のむ', en: 'to drink' }, '食べる': { r: 'たべる', en: 'to eat' }, '読む': { r: 'よむ', en: 'to read' }, '歩く': { r: 'あるく', en: 'to walk' },
  '言う': { r: 'いう', en: 'to say' }, '聞く': { r: 'きく', en: 'to ask, to hear' }, '会う': { r: 'あう', en: 'to meet' }, '使う': { r: 'つかう', en: 'to use' }, '座る': { r: 'すわる', en: 'to sit' },
  '休む': { r: 'やすむ', en: 'to rest, to take time off' }, '持つ': { r: 'もつ', en: 'to hold, to have' }, '忘れる': { r: 'わすれる', en: 'to forget, to leave behind' }, '遅れる': { r: 'おくれる', en: 'to be late' },
  '終わる': { r: 'おわる', en: 'to end, to finish' }, '始める': { r: 'はじめる', en: 'to start (something)' }, '始まる': { r: 'はじまる', en: 'to start (by itself)' }, '降る': { r: 'ふる', en: 'to fall (rain, snow)' },
  '疲れる': { r: 'つかれる', en: 'to get tired' }, '延びる': { r: 'のびる', en: 'to be extended, postponed' }, '届く': { r: 'とどく', en: 'to arrive (a delivery)' }, '替わる': { r: 'かわる', en: 'to swap, to change places' },
  '開ける': { r: 'あける', en: 'to open (something)' }, '開く': { r: 'あく', en: 'to open (by itself)' }, '閉まる': { r: 'しまる', en: 'to close (by itself)' }, '閉める': { r: 'しめる', en: 'to close (something)' },
  'すく': { en: 'to become empty (お腹がすく = get hungry)' }, '曲がる': { r: 'まがる', en: 'to turn' }, '取る': { r: 'とる', en: 'to take, to pass (me)' }, '貸す': { r: 'かす', en: 'to lend' },
  '返す': { r: 'かえす', en: 'to give back' }, '借りる': { r: 'かりる', en: 'to borrow' }, '置く': { r: 'おく', en: 'to put down' }, '落とす': { r: 'おとす', en: 'to drop' }, '鳴る': { r: 'なる', en: 'to ring, to sound' },
  '渡す': { r: 'わたす', en: 'to hand over' }, '呼ぶ': { r: 'よぶ', en: 'to call (someone over)' }, '立つ': { r: 'たつ', en: 'to stand' }, '要る': { r: 'いる', en: 'to need' }, '知る': { r: 'しる', en: 'to know (知ってる = I know)' },
  '慣れる': { r: 'なれる', en: 'to get used to' }, '寝る': { r: 'ねる', en: 'to sleep, to go to bed' }, '通る': { r: 'とおる', en: 'to go through, to pass' }, '頼む': { r: 'たのむ', en: 'to ask, to rely on (頼むよ = I\'m counting on you)' },
  '願い': { r: 'ねがい', en: 'request (お願い = please)' }, '待ち': { r: 'まち', en: 'waiting (お待ちください = please wait)' },
  '動く': { r: 'うごく', en: 'to move, to run (machines)' }, '止まる': { r: 'とまる', en: 'to stop' }, '止める': { r: 'とめる', en: 'to stop (something)' }, '落ちる': { r: 'おちる', en: 'to fall' },
  '出る': { r: 'でる', en: 'to come out, to leave' }, '出す': { r: 'だす', en: 'to put out, to take out' }, '急ぐ': { r: 'いそぐ', en: 'to hurry' }, '飛ぶ': { r: 'とぶ', en: 'to fly' },
  'つく': { en: 'to come on (a light)' }, '消える': { r: 'きえる', en: 'to go out, to vanish' }, '起きる': { r: 'おきる', en: 'to wake up' }, '回る': { r: 'まわる', en: 'to spin, to turn' },
  // katakana words
  'コーヒー': { en: 'coffee' }, 'コピー': { en: 'copy' }, 'パソコン': { en: 'computer, PC' }, 'エアコン': { en: 'air conditioner' }, 'ドア': { en: 'door' }, 'トイレ': { en: 'toilet' },
  'シャツ': { en: 'shirt' }, 'ペン': { en: 'pen' }, 'カメラ': { en: 'camera' }, 'ビール': { en: 'beer' }, 'エレベーター': { en: 'lift, elevator' }, 'シティ': { en: 'city' },
  'バックアップ': { en: 'backup' }, 'カード': { en: 'card' }, 'トマト': { en: 'tomato' }, 'パン': { en: 'bread' }, 'ケーキ': { en: 'cake' }, 'ピザ': { en: 'pizza' }, 'テレビ': { en: 'TV' },
  'バス': { en: 'bus' }, 'ギター': { en: 'guitar' }, 'ピアノ': { en: 'piano' }, 'タクシー': { en: 'taxi' }, 'ランプ': { en: 'lamp' }, 'ワイン': { en: 'wine' }, 'チーズ': { en: 'cheese' },
  'クッキー': { en: 'biscuit, cookie' }, 'アイス': { en: 'ice cream' }, 'ロボット': { en: 'robot' }, 'ロケット': { en: 'rocket' }, 'トラック': { en: 'lorry, truck' }, 'テント': { en: 'tent' },
  'マイク': { en: 'microphone' }, 'ノート': { en: 'notebook' }, 'シャワー': { en: 'shower' }, 'ソファ': { en: 'sofa' }, 'バッグ': { en: 'bag' }, 'オレンジ': { en: 'orange' }, 'ボール': { en: 'ball' },
  'ハンバーガー': { en: 'hamburger' }, 'スーツケース': { en: 'suitcase' }, 'ヘッドホン': { en: 'headphones' }, 'プリンター': { en: 'printer' }, 'スマホ': { en: 'smartphone' }, 'ゲーム': { en: 'game, video game' },
  'ポップコーン': { en: 'popcorn' }, 'キーボード': { en: 'keyboard' }, 'カレンダー': { en: 'calendar' }, 'トロフィー': { en: 'trophy' }, 'フォーク': { en: 'fork' }, 'バスケットボール': { en: 'basketball' }, 'タブレット': { en: 'tablet' },
};
export const SPELL_KEYS = ['座る', '休む', '始める', '帰る'];

// Kanji tiers come from the JLPT levels in data/lang/kanji.json (N5 = 1, N4 = 2, N3 = 3, N2 = 4, rest = 5).
export { KANJI_TIER } from './data.js';
