import bakery from './bakery.js';
import train from './train.js';
import gate from './gate.js';
import forecourt from './forecourt.js';
import office from './office.js';
import plaza from './plaza.js';
import canteen from './canteen.js';
import dorm_court from './dorm_court.js';
import dorms from './dorms.js';
import east_lane from './east_lane.js';
import east_coast from './east_coast.js';
import sports from './sports.js';
import pool from './pool.js';
import gym from './gym.js';
import shotengai from './shotengai.js';
import izakaya from './izakaya.js';
import karaoke from './karaoke.js';
import karaoke_booth from './karaoke_booth.js';
import dorm_commons from './dorm_commons.js';
import office_quarter from './office_quarter.js';
import harbour from './harbour.js';
import works from './works.js';
export const STORIES = { bakery, train, gate, forecourt, office, plaza, canteen, dorm_court, dorms, east_lane, east_coast, sports, pool, gym, shotengai, izakaya, karaoke, karaoke_booth, dorm_commons, office_quarter, harbour, works };
export { TRIPS } from './routes.js';
