"""Every sound effect and ambience bed the island slice needs, with its candidates.
Each entry: name -> dict(desc, hooks (the builder's audio.gd sfx names it can replace), kind ('one' one-shot, 'loop', 'steps' a set of
single footsteps), kenney (list of 'pack/file.ogg' CC0 candidates), sa3 (list of (prompt, seconds)) for Stable Audio 3 Medium.
Placeholders until Jørgen approves them on legacy/proto2/island-audio."""

SFX = {
    # footsteps: sets of single steps, the game picks one at random per footfall
    'step_tile': dict(desc='Footsteps on the lobby and plaza tile', kind='steps', hooks=[],
                      kenney=['impact-sounds/footstep_concrete_000.ogg'],  # processed brighter as a stand-in for tile (see sfx_build.py)
                      sa3=[('Footsteps of leather office shoes walking slowly on a hard polished ceramic tile floor in a quiet lobby, close, clean, dry, no music.', 6)]),
    'step_carpet': dict(desc='Footsteps on the office and executive-floor carpet', kind='steps', hooks=[],
                        kenney=[f'impact-sounds/footstep_carpet_00{i}.ogg' for i in range(5)], sa3=[]),
    'step_concrete': dict(desc='Footsteps on the B2 corridor, car park and street concrete', kind='steps', hooks=[],
                          kenney=[f'impact-sounds/footstep_concrete_00{i}.ogg' for i in range(5)], sa3=[]),
    # doors
    'door_open': dict(desc='The office door opening', kind='one', hooks=['door'],
                      kenney=['rpg-audio/doorOpen_1.ogg', 'rpg-audio/doorOpen_2.ogg'],
                      sa3=[('An office door with a metal handle opening, latch click and a short creak, indoors, close.', 2)]),
    'door_close': dict(desc='The office door closing', kind='one', hooks=[],
                       kenney=['rpg-audio/doorClose_1.ogg', 'rpg-audio/doorClose_2.ogg', 'rpg-audio/doorClose_4.ogg'],
                       sa3=[('An office door closing with a firm latch click, indoors, close.', 2)]),
    'door_locked': dict(desc='A locked door handle jiggling (the twitch on a door)', kind='one', hooks=[],
                        kenney=['rpg-audio/metalLatch.ogg'],
                        sa3=[('A locked door: the metal handle is pushed down twice and rattles, the lock holds.', 2)]),
    'key': dict(desc='A key turning in an old door lock (room 203 at H01: played twice, the lock sticks the first time)', kind='one',
                hooks=['key'],
                kenney=['rpg-audio/metalLatch.ogg', 'rpg-audio/metalClick.ogg'],
                sa3=[('A metal key turning in an old door lock: a short scrape and a solid click, close, indoors.', 2),
                     ('A key sliding into an old lock and turning with a stiff mechanical click.', 2)]),
    'glassdoor_slide': dict(desc='The lobby glass doors sliding open', kind='one', hooks=[],
                            kenney=[], sa3=[('Automatic glass sliding doors opening at a building entrance, soft motor hum and a smooth slide.', 3)]),
    # lift
    'lift_chime': dict(desc='Lift arrival chime', kind='one', hooks=['chime'],
                       kenney=['interface-sounds/bong_001.ogg'],
                       sa3=[('A single soft elevator arrival chime, a gentle two-tone ding, clean, in a quiet building.', 2)]),
    'lift_doors': dict(desc='Lift doors sliding open or shut', kind='one', hooks=[],
                       kenney=['sci-fi-sounds/doorOpen_000.ogg', 'sci-fi-sounds/doorClose_000.ogg'],
                       sa3=[('Elevator doors sliding open with a soft mechanical rumble and a light thud, indoors.', 3)]),
    'lift_ride': dict(desc='Inside the moving lift (loop)', kind='loop', hooks=[],
                      kenney=['sci-fi-sounds/spaceEngineLow_000.ogg'],
                      sa3=[('Inside a moving elevator: a low steady hum and a faint whoosh of air, no music.', 8)]),
    # turnstile
    'turnstile_beep': dict(desc='Card reader accepts a card', kind='one', hooks=['beep'],
                           kenney=['digital-audio/twoTone1.ogg', 'digital-audio/tone1.ogg', 'interface-sounds/confirmation_001.ogg'],
                           sa3=[('A short electronic beep from an office security card reader, one clean high tone.', 1)]),
    'turnstile_error': dict(desc='Card reader refuses: the red light buzz', kind='one', hooks=['buzz'],
                            kenney=['interface-sounds/error_006.ogg', 'digital-audio/lowDown.ogg', 'interface-sounds/error_003.ogg'],
                            sa3=[('A security gate error buzzer, three short low electronic buzzes.', 2)]),
    'turnstile_jam': dict(desc='The turnstile flap sticking halfway and rattling', kind='one', hooks=[],
                          kenney=['impact-sounds/impactMetal_light_002.ogg'],
                          sa3=[('A metal and glass turnstile flap stuck halfway, rattling and clanking against its frame, a motor straining.', 3)]),
    'turnstile_open': dict(desc='The turnstile flaps swinging open', kind='one', hooks=[],
                           kenney=[], sa3=[('Glass turnstile flaps swinging open with a soft pneumatic whoosh and a click.', 2)]),
    'thump': dict(desc="Ishibashi's gloved hand thumping the flap", kind='one', hooks=['thump'],
                  kenney=['impact-sounds/impactPlate_medium_001.ogg', 'impact-sounds/impactMetal_medium_002.ogg', 'impact-sounds/impactPunch_medium_000.ogg'],
                  sa3=[]),
    # copier
    'copier_start': dict(desc='The copier waking: fans spin up, lights come on', kind='one', hooks=['wake'],
                         kenney=['sci-fi-sounds/computerNoise_000.ogg'],
                         sa3=[('An old office photocopier powering up: relays clicking, fans spinning up, a motor whirring into life.', 4)]),
    'copier_run': dict(desc='The copier printing (loop)', kind='loop', hooks=['print'],
                       kenney=[], sa3=[('An office photocopier printing copies: rhythmic paper feeding, rollers turning, steady and regular.', 8)]),
    'copier_jam': dict(desc='The copier jamming', kind='one', hooks=[],
                       kenney=[], sa3=[('A photocopier paper jam: grinding rollers, crumpling paper, a hard mechanical clunk, then the motor stops.', 3)]),
    'copier_spew': dict(desc='The copier spitting paper from every slot (loop)', kind='loop', hooks=[],
                        kenney=[], sa3=[('A machine rapidly spitting out loose sheets of paper, paper flapping and fluttering, a motor running fast.', 6)]),
    'copier_hum': dict(desc='The copier idling after the job (loop)', kind='loop', hooks=['hum'],
                       kenney=['sci-fi-sounds/spaceEngineSmall_000.ogg'],
                       sa3=[('A photocopier idling, a soft steady fan hum, quiet room.', 8)]),
    'power_down': dict(desc='A machine switching off: the copier with its plug pulled (gates, the jam), a falling hum', kind='one',
                       hooks=['power_down'],
                       kenney=['digital-audio/lowDown.ogg', 'digital-audio/phaserDown2.ogg'],
                       sa3=[('An old office photocopier losing power: its fans and motor spin down, the hum falls in pitch and fades out, a last relay click.', 3),
                            ('An electric machine switching off: a low hum sliding down in pitch and fading to silence, indoors.', 3)]),
    'paper': dict(desc='Paper handled: the copies, the document, a page turn', kind='one', hooks=['page'],
                  kenney=['rpg-audio/bookFlip1.ogg', 'rpg-audio/bookFlip2.ogg', 'rpg-audio/bookPlace1.ogg'], sa3=[]),
    'stapler': dict(desc='One staple through the copies', kind='one', hooks=[],
                    kenney=['rpg-audio/metalClick.ogg'], sa3=[('A desk stapler pressed once, a crisp metal crunch.', 1)]),
    # vending machine
    'vending_clunk': dict(desc='A can dropping into the vending machine tray', kind='one', hooks=['can'],
                          kenney=['impact-sounds/impactMetal_heavy_001.ogg'],
                          sa3=[('A drink can dropping inside a vending machine into the tray, a heavy metallic clunk.', 2)]),
    'vending_hum': dict(desc='The vending machine running (loop)', kind='loop', hooks=[],
                        kenney=[], sa3=[('A vending machine compressor humming steadily, a low electric drone.', 8)]),
    'coins': dict(desc='Coins: into the machine, back out of the return slot', kind='one', hooks=['coin'],
                  kenney=['rpg-audio/handleCoins.ogg', 'rpg-audio/handleCoins2.ogg', 'casino-audio/chips-collide-1.ogg'],
                  sa3=[('A few coins dropping into a metal coin return slot of a vending machine, bright jingling.', 2)]),
    'kick': dict(desc="Mio kicking the vending machine", kind='one', hooks=['kick'],
                 kenney=['impact-sounds/impactMetal_heavy_003.ogg', 'impact-sounds/impactPunch_heavy_001.ogg'], sa3=[]),
    # the basement
    'fluorescent_buzz': dict(desc='Fluorescent tubes humming in the B2 corridor (loop)', kind='loop', hooks=[],
                             kenney=['sci-fi-sounds/forceField_000.ogg'],
                             sa3=[('Fluorescent tube lights humming and buzzing in a quiet basement corridor, a steady electrical buzz.', 8)]),
    'lights_on': dict(desc='Tubes flickering on, one after another', kind='one', hooks=['lights'],
                      kenney=[], sa3=[('Fluorescent tube lights flickering on one after another: ticking starters, electric pings, the buzz rising.', 4)]),
    'fan_hum': dict(desc='An old desk fan running (loop)', kind='loop', hooks=[],
                    kenney=['sci-fi-sounds/spaceEngineLow_001.ogg'],
                    sa3=[('An old electric desk fan running, a steady soft whirr and a faint rattle.', 8)]),
    'clock_tick': dict(desc='The old wall clock ticking (loop, one tick a second)', kind='loop', hooks=['tick'],
                       kenney=['interface-sounds/tick_002.ogg'],
                       sa3=[('An old wall clock ticking steadily, one tick per second, in a silent room.', 8)]),
    'coffee_maker': dict(desc='The kitchenette coffee maker gurgling', kind='one', hooks=[],
                         kenney=[], sa3=[('A drip coffee maker gurgling and hissing as hot water runs through, a few bubbling pops.', 5)]),
    # phone and the rest
    'phone_buzz': dict(desc="The company phone buzzing with a message", kind='one', hooks=[],
                       kenney=[], sa3=[('A smartphone vibrating twice on a hard surface, short buzzes.', 2)]),
    'shutter': dict(desc="Emi's phone camera", kind='one', hooks=['shutter'],
                    kenney=[], sa3=[('A smartphone camera shutter sound, one short click.', 1)]),
    'tambourine': dict(desc="The player's tambourine tap in the karaoke", kind='one', hooks=[],
                       kenney=[], sa3=[('A single tambourine hit, bright jingles, dry, close microphone.', 1)]),
    'monorail_depart': dict(desc='A01: the monorail pulling out of the station', kind='one', hooks=[],
                            kenney=[], sa3=[('A monorail train pulling away from an elevated station: an electric motor whine rising and fading into the distance, seagulls.', 10)]),
    # UI and the magic
    'ui_click': dict(desc='Taps, buttons', kind='one', hooks=['tap'],
                     kenney=['ui-audio/click1.ogg', 'ui-audio/click3.ogg', 'interface-sounds/click_002.ogg'], sa3=[]),
    'ui_select': dict(desc='Choosing a reply, a chip, a word', kind='one', hooks=[],
                      kenney=['interface-sounds/select_002.ogg', 'interface-sounds/select_005.ogg'], sa3=[]),
    'ui_open': dict(desc='The phone or the notebook sliding up', kind='one', hooks=[],
                    kenney=['interface-sounds/maximize_003.ogg', 'interface-sounds/maximize_006.ogg'], sa3=[]),
    'ui_close': dict(desc='The phone or the notebook closing', kind='one', hooks=[],
                     kenney=['interface-sounds/minimize_003.ogg', 'interface-sounds/minimize_006.ogg'], sa3=[]),
    'ui_error': dict(desc='Nothing understood (soft)', kind='one', hooks=['fail'],
                     kenney=['interface-sounds/error_004.ogg', 'interface-sounds/error_008.ogg'], sa3=[]),
    'catch': dict(desc='A word caught into ことば', kind='one', hooks=['catch'],
                  kenney=['interface-sounds/confirmation_002.ogg', 'interface-sounds/pluck_001.ogg', 'interface-sounds/glass_002.ogg'], sa3=[]),
    'say': dict(desc='A command sent: the kana leave the bar', kind='one', hooks=['say'],
                kenney=['digital-audio/phaserUp2.ogg', 'interface-sounds/scratch_002.ogg'],
                sa3=[('A short soft airy whoosh, like a breath of wind passing by, clean.', 1)]),
    'command_land': dict(desc='The command landing on its target (the chime)', kind='one', hooks=['pass'],
                         kenney=['music-jingles/jingles_STEEL00.ogg', 'music-jingles/jingles_PIZZI00.ogg', 'interface-sounds/glass_005.ogg'],
                         sa3=[('A soft magical chime with a glassy shimmer, a short rising sparkle, clean, no music.', 2)]),
    'twitch': dict(desc='A machine twitching toward the action (right verb, wrong form)', kind='one', hooks=['twitch'],
                   kenney=['interface-sounds/switch_003.ogg', 'rpg-audio/metalClick.ogg'],
                   sa3=[('A tiny mechanical twitch: a small motor jolts once, a click, then stops.', 1)]),
    'stutter': dict(desc='A verb built with the wrong rule: half a twitch', kind='one', hooks=['stutter'],
                    kenney=['interface-sounds/glitch_002.ogg', 'interface-sounds/glitch_004.ogg'],
                    sa3=[('A small machine motor stuttering: it catches and fails three times quickly.', 1.5)]),
    'rule': dict(desc='The command-form rule unlocking in the notebook', kind='one', hooks=['rule'],
                 kenney=['music-jingles/jingles_PIZZI04.ogg', 'music-jingles/jingles_STEEL04.ogg', 'music-jingles/jingles_NES04.ogg'], sa3=[]),
}

# Ambience beds, looped quietly under the scene (the builder's amb hook).
AMB = {
    'amb_plaza': dict(desc='The station plaza by the sea, morning', kind='loop', hooks=[],
                      kenney=[], sa3=[('Outdoor plaza by the sea on a sunny morning: distant seagulls, light wind, soft footsteps of commuters, a faint city hum.', 30)]),
    'amb_lobby': dict(desc='The lobby in the morning', kind='loop', hooks=[],
                      kenney=[], sa3=[('A large office building lobby in the morning: a soft murmur of people, footsteps on tile, air conditioning.', 30)]),
    'amb_basement': dict(desc='B2 by day: vents and pipes', kind='loop', hooks=[],
                         kenney=[], sa3=[('A quiet basement corridor: a low ventilation hum, a faint fluorescent buzz, distant water in pipes.', 30)]),
    'amb_karaoke': dict(desc='The karaoke corridor: muffled singing behind doors', kind='loop', hooks=[],
                        kenney=[], sa3=[('A karaoke box corridor: muffled pop singing and music from behind closed doors, people laughing faintly.', 30)]),
    'amb_night': dict(desc='The building at night, nearly silent', kind='loop', hooks=[],
                      kenney=[], sa3=[('A silent office building at night: a very faint electrical hum and a distant air vent.', 30)]),
    'amb_dorm': dict(desc='The dorm room at night', kind='loop', hooks=[],
                     kenney=[], sa3=[('A tiny apartment at night: faint traffic far outside, a small refrigerator humming.', 30)]),
}

ALL = {**SFX, **AMB}
SA3_TAKES = 2  # seeds per prompt
