"""Write data/lang/kana.json (the letters track: every kana with romaji, row and group, plus look-alike sets)
and data/lang/romaji.js (a small ES module: toRomaji(kana), toHiragana(katakana)).

Romaji style: Hepburn as used in the level check (カード = kaado, コピー = kopii): long vowels written
double, っ doubles the next consonant (っち = tchi), ん before a vowel or y = n'.
"""
import json
import os

from common import OUT, hira2kata

BASIC = [
    ('', 'あいうえお', ['a', 'i', 'u', 'e', 'o']),
    ('k', 'かきくけこ', ['ka', 'ki', 'ku', 'ke', 'ko']),
    ('s', 'さしすせそ', ['sa', 'shi', 'su', 'se', 'so']),
    ('t', 'たちつてと', ['ta', 'chi', 'tsu', 'te', 'to']),
    ('n', 'なにぬねの', ['na', 'ni', 'nu', 'ne', 'no']),
    ('h', 'はひふへほ', ['ha', 'hi', 'fu', 'he', 'ho']),
    ('m', 'まみむめも', ['ma', 'mi', 'mu', 'me', 'mo']),
    ('y', 'やゆよ', ['ya', 'yu', 'yo']),
    ('r', 'らりるれろ', ['ra', 'ri', 'ru', 're', 'ro']),
    ('w', 'わを', ['wa', 'o']),
    ('n', 'ん', ['n']),
]
DAKUTEN = [
    ('g', 'がぎぐげご', ['ga', 'gi', 'gu', 'ge', 'go']),
    ('z', 'ざじずぜぞ', ['za', 'ji', 'zu', 'ze', 'zo']),
    ('d', 'だぢづでど', ['da', 'ji', 'zu', 'de', 'do']),
    ('b', 'ばびぶべぼ', ['ba', 'bi', 'bu', 'be', 'bo']),
    ('p', 'ぱぴぷぺぽ', ['pa', 'pi', 'pu', 'pe', 'po']),
]
YOUON_BASE = {'き': 'k', 'し': 'sh', 'ち': 'ch', 'に': 'n', 'ひ': 'h', 'み': 'm', 'り': 'r',
              'ぎ': 'g', 'じ': 'j', 'び': 'b', 'ぴ': 'p', 'ぢ': 'j'}
SMALL_Y = {'ゃ': 'a', 'ゅ': 'u', 'ょ': 'o'}
# katakana-only combinations for loanwords
EXTENDED = {
    'ティ': 'ti', 'ディ': 'di', 'トゥ': 'tu', 'ドゥ': 'du', 'ファ': 'fa', 'フィ': 'fi', 'フェ': 'fe', 'フォ': 'fo',
    'ウィ': 'wi', 'ウェ': 'we', 'ウォ': 'wo', 'ヴァ': 'va', 'ヴィ': 'vi', 'ヴ': 'vu', 'ヴェ': 've', 'ヴォ': 'vo',
    'シェ': 'she', 'ジェ': 'je', 'チェ': 'che', 'ツァ': 'tsa', 'イェ': 'ye', 'デュ': 'dyu', 'テュ': 'tyu',
}
LOOKALIKES = {
    'katakana': [['シ', 'ツ'], ['ソ', 'ン'], ['シ', 'ツ', 'ソ', 'ン'], ['ク', 'ケ', 'タ'], ['コ', 'ユ', 'ロ'], ['ウ', 'ワ', 'フ'],
                 ['ヌ', 'メ', 'ス'], ['チ', 'テ'], ['マ', 'ム'], ['ル', 'レ'], ['ノ', 'メ'], ['ラ', 'ヲ']],
    'hiragana': [['ぬ', 'め'], ['ね', 'れ', 'わ'], ['さ', 'ち'], ['は', 'ほ'], ['る', 'ろ'], ['き', 'さ'], ['い', 'り'],
                 ['あ', 'お'], ['ま', 'も'], ['く', 'へ']],
}


def table():
    rows = []
    for group, data in (('basic', BASIC), ('dakuten', DAKUTEN)):
        for row, chars, roms in data:
            for c, r in zip(chars, roms):
                rows.append({'h': c, 'k': hira2kata(c), 'r': r, 'row': row or 'a', 'group': group})
    for base, cons in YOUON_BASE.items():
        for small, v in SMALL_Y.items():
            r = cons + v if cons.endswith(('sh', 'ch', 'j')) else cons + 'y' + v
            rows.append({'h': base + small, 'k': hira2kata(base + small), 'r': r, 'row': cons[0], 'group': 'youon'})
    for k, r in EXTENDED.items():
        rows.append({'h': None, 'k': k, 'r': r, 'row': r[0], 'group': 'extended'})
    return rows


JS = r'''// Generated by tools/lang/build_kana.py. Kana to romaji (Hepburn, long vowels doubled: カード = kaado).
const T = __TABLE__;
const SMALL_VOWEL = { 'ぁ': 'a', 'ぃ': 'i', 'ぅ': 'u', 'ぇ': 'e', 'ぉ': 'o' };
export function toHiragana(s) {
  return s.replace(/[ァ-ヶ]/g, (c) => String.fromCharCode(c.charCodeAt(0) - 0x60));
}
export function toRomaji(kana) {
  const s = kana;
  let out = '';
  for (let i = 0; i < s.length; i++) {
    const two = s.slice(i, i + 2);
    const hk = toHiragana(two);
    if (T[two] || (two.length === 2 && T[hk] && /[ゃゅょ]/.test(hk[1]))) { out += T[two] || T[hk]; i++; continue; }
    const c = s[i];
    const h = toHiragana(c);
    if (h === 'っ') {
      const next = toRomaji(s.slice(i + 1, i + 3));
      out += next.startsWith('ch') ? 't' : (next[0] && !'aeiou'.includes(next[0]) ? next[0] : '');
      continue;
    }
    if (c === 'ー') { const m = out.match(/[aeiou]$/); out += m ? m[0] : '-'; continue; }
    if (h === 'ん') {
      const next = toHiragana(s[i + 1] || '');
      out += /[あいうえおやゆよ]/.test(next) ? "n'" : 'n';
      continue;
    }
    if (SMALL_VOWEL[h]) { out = out.replace(/[aeiou]$/, '') + SMALL_VOWEL[h]; continue; }
    out += T[c] || T[h] || c;
  }
  return out;
}
'''


def main():
    rows = table()
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, 'kana.json'), 'w', encoding='utf-8') as f:
        json.dump({'about': 'Kana for the letters track. h hiragana, k katakana, r romaji (Hepburn), row consonant row, '
                            'group basic/dakuten/youon/extended (katakana-only loanword sounds). lookalikes: sets that '
                            'learners mix up (Jørgen: ソ/ン/シ/ツ, ぬ/め/ね). Rules: っ doubles the next consonant, ー repeats '
                            'the vowel (カード = kaado), ん before a vowel or y = n\'. data/lang/romaji.js implements this.',
                   'kana': rows, 'lookalikes': LOOKALIKES}, f, ensure_ascii=False, indent=0)
    t = {}
    for r in rows:
        if r['h']:
            t[r['h']] = r['r']
        t[r['k']] = r['r']
    with open(os.path.join(OUT, 'romaji.js'), 'w', encoding='utf-8') as f:
        f.write(JS.replace('__TABLE__', json.dumps(t, ensure_ascii=False)))
    print(len(rows), 'kana rows')


if __name__ == '__main__':
    main()
